# golangci-lint configuration for Farmers Module
run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused

linters-settings:
  goimports:
    local-prefixes: github.com/Kisanlink/farmers-module

issues:
  exclude-dirs:
    - vendor
    - docs
    - scripts
    - pkg
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_gen\\.go$"
    - "docs/docs\\.go$"
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - linters:
        - staticcheck
      text: "SA9003:"

  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 3
