run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - structcheck
    - deadcode
    - varcheck
    - ineffassign
    - typecheck
    - gofmt
    - goimports
    - misspell
    - revive

issues:
  exclude-use-default: false
