package services

import (
	"github.com/Kisanlink/farmers-module/models"
	"github.com/Kisanlink/farmers-module/repositories"
)

// FarmerServiceInterface defines service methods for farmer operations
type FarmerServiceInterface interface {
	CreateFarmer(userID string, req models.FarmerSignupRequest) (*models.Farmer, error)
}

// FarmerService handles business logic for farmers
type FarmerService struct {
	repo repositories.FarmerRepositoryInterface
}

// NewFarmerService initializes a new FarmerService
func NewFarmerService(repo repositories.FarmerRepositoryInterface) *FarmerService {
	return &FarmerService{repo: repo}
}

// CreateFarmer creates a new farmer entry
func (s *FarmerService) CreateFarmer(userID string, req models.FarmerSignupRequest) (*models.Farmer, error) {
	newFarmer := &models.Farmer{
		UserID:           userID, // user_id from AAA service
		KisansathiUserID: req.KisansathiUserID,
		IsActive:         true,
	}

	// The ID will be generated by the BeforeCreate hook in the Base model
	return s.repo.CreateFarmerEntry(newFarmer)
}
