// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/identity/farmers": {
            "get": {
                "description": "List farmers with filtering and pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "identity"
                ],
                "summary": "List farmers",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "AAA Org ID filter",
                        "name": "aaa_org_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "KisanSathi User ID filter",
                        "name": "kisan_sathi_user_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Kisanlink_farmers-module_internal_entities_responses.FarmerListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Kisanlink_farmers-module_internal_entities_responses.BaseResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Kisanlink_farmers-module_internal_entities_responses.BaseResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new farmer profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "identity"
                ],
                "summary": "Create a new farmer",
                "parameters": [
                    {
                        "description": "Farmer data",
                        "name": "farmer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_Kisanlink_farmers-module_internal_entities_responses.FarmerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Kisanlink_farmers-module_internal_entities_responses.BaseResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_Kisanlink_farmers-module_internal_entities_responses.BaseResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Kisanlink_farmers-module_internal_entities_responses.BaseResponse"
                        }
                    }
                }
            }
        },
        "/identity/farmers/{aaa_user_id}/{aaa_org_id}": {
            "get": {
                "description": "Retrieve a farmer profile by AAA user ID and org ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "identity"
                ],
                "summary": "Get farmer by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AAA User ID",
                        "name": "aaa_user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "AAA Org ID",
                        "name": "aaa_org_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Kisanlink_farmers-module_internal_entities_responses.FarmerProfileResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Kisanlink_farmers-module_internal_entities_responses.BaseResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_Kisanlink_farmers-module_internal_entities_responses.BaseResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Kisanlink_farmers-module_internal_entities_responses.BaseResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing farmer profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "identity"
                ],
                "summary": "Update farmer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AAA User ID",
                        "name": "aaa_user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "AAA Org ID",
                        "name": "aaa_org_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Farmer update data",
                        "name": "farmer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Kisanlink_farmers-module_internal_entities_responses.FarmerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Kisanlink_farmers-module_internal_entities_responses.BaseResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_Kisanlink_farmers-module_internal_entities_responses.BaseResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Kisanlink_farmers-module_internal_entities_responses.BaseResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a farmer profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "identity"
                ],
                "summary": "Delete farmer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AAA User ID",
                        "name": "aaa_user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "AAA Org ID",
                        "name": "aaa_org_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Kisanlink_farmers-module_internal_entities_responses.BaseResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Kisanlink_farmers-module_internal_entities_responses.BaseResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_Kisanlink_farmers-module_internal_entities_responses.BaseResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Kisanlink_farmers-module_internal_entities_responses.BaseResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "base.PaginationInfo": {
            "type": "object",
            "properties": {
                "has_next": {
                    "type": "boolean"
                },
                "has_prev": {
                    "type": "boolean"
                },
                "page": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "github_com_Kisanlink_farmers-module_internal_entities_farm.Geometry": {
            "type": "object",
            "properties": {
                "wkb": {
                    "description": "Well-Known Binary format",
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "format": "int32"
                    }
                },
                "wkt": {
                    "description": "Well-Known Text format",
                    "type": "string"
                }
            }
        },
        "github_com_Kisanlink_farmers-module_internal_entities_responses.AddressData": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string"
                },
                "coordinates": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "postal_code": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "street_address": {
                    "type": "string"
                }
            }
        },
        "github_com_Kisanlink_farmers-module_internal_entities_responses.BaseResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {},
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "github_com_Kisanlink_farmers-module_internal_entities_responses.FarmData": {
            "type": "object",
            "properties": {
                "aaa_farmer_user_id": {
                    "type": "string"
                },
                "aaa_org_id": {
                    "type": "string"
                },
                "area_ha": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "deleted_by": {
                    "type": "string"
                },
                "geometry": {
                    "$ref": "#/definitions/github_com_Kisanlink_farmers-module_internal_entities_farm.Geometry"
                },
                "id": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "string"
                }
            }
        },
        "github_com_Kisanlink_farmers-module_internal_entities_responses.FarmerListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Kisanlink_farmers-module_internal_entities_responses.FarmerProfileData"
                    }
                },
                "error": {},
                "message": {
                    "type": "string"
                },
                "pagination": {
                    "$ref": "#/definitions/base.PaginationInfo"
                },
                "request_id": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "github_com_Kisanlink_farmers-module_internal_entities_responses.FarmerProfileData": {
            "type": "object",
            "properties": {
                "aaa_org_id": {
                    "type": "string"
                },
                "aaa_user_id": {
                    "type": "string"
                },
                "address": {
                    "$ref": "#/definitions/github_com_Kisanlink_farmers-module_internal_entities_responses.AddressData"
                },
                "created_at": {
                    "type": "string"
                },
                "date_of_birth": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "farms": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Kisanlink_farmers-module_internal_entities_responses.FarmData"
                    }
                },
                "first_name": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "kisan_sathi_user_id": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "phone_number": {
                    "type": "string"
                },
                "preferences": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_Kisanlink_farmers-module_internal_entities_responses.FarmerProfileResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_Kisanlink_farmers-module_internal_entities_responses.FarmerProfileData"
                },
                "error": {},
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "github_com_Kisanlink_farmers-module_internal_entities_responses.FarmerResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_Kisanlink_farmers-module_internal_entities_responses.FarmerProfileData"
                },
                "error": {},
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Farmers Module API",
	Description:      "Farmers Module Service with Workflow-Based Architecture for Farm Management",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
