// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: attribute.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Attribute model
type Attribute struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SubjectId      string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	SubjectType    string                 `protobuf:"bytes,3,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"` // "principal", "resource", "organization"
	Key            string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Value          *structpb.Struct       `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	OrganizationId string                 `protobuf:"bytes,6,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	IsActive       bool                   `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	SetById        string                 `protobuf:"bytes,9,opt,name=set_by_id,json=setById,proto3" json:"set_by_id,omitempty"`
	Metadata       *structpb.Struct       `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Attribute) Reset() {
	*x = Attribute{}
	mi := &file_attribute_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attribute) ProtoMessage() {}

func (x *Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_attribute_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attribute.ProtoReflect.Descriptor instead.
func (*Attribute) Descriptor() ([]byte, []int) {
	return file_attribute_proto_rawDescGZIP(), []int{0}
}

func (x *Attribute) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Attribute) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *Attribute) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *Attribute) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Attribute) GetValue() *structpb.Struct {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Attribute) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Attribute) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Attribute) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Attribute) GetSetById() string {
	if x != nil {
		return x.SetById
	}
	return ""
}

func (x *Attribute) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Attribute) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Attribute) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Set Attributes Request
type SetAttributesRequest struct {
	state          protoimpl.MessageState     `protogen:"open.v1"`
	SubjectId      string                     `protobuf:"bytes,1,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	SubjectType    string                     `protobuf:"bytes,2,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	Attributes     map[string]*structpb.Value `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Key-value pairs
	ExpiresAt      *timestamppb.Timestamp     `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	OrganizationId string                     `protobuf:"bytes,5,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetAttributesRequest) Reset() {
	*x = SetAttributesRequest{}
	mi := &file_attribute_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAttributesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAttributesRequest) ProtoMessage() {}

func (x *SetAttributesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attribute_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAttributesRequest.ProtoReflect.Descriptor instead.
func (*SetAttributesRequest) Descriptor() ([]byte, []int) {
	return file_attribute_proto_rawDescGZIP(), []int{1}
}

func (x *SetAttributesRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *SetAttributesRequest) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *SetAttributesRequest) GetAttributes() map[string]*structpb.Value {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *SetAttributesRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *SetAttributesRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

// Set Attributes Response
type SetAttributesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Attributes    []*Attribute           `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAttributesResponse) Reset() {
	*x = SetAttributesResponse{}
	mi := &file_attribute_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAttributesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAttributesResponse) ProtoMessage() {}

func (x *SetAttributesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attribute_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAttributesResponse.ProtoReflect.Descriptor instead.
func (*SetAttributesResponse) Descriptor() ([]byte, []int) {
	return file_attribute_proto_rawDescGZIP(), []int{2}
}

func (x *SetAttributesResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *SetAttributesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SetAttributesResponse) GetAttributes() []*Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// Get Attributes Request
type GetAttributesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubjectId      string                 `protobuf:"bytes,1,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	SubjectType    string                 `protobuf:"bytes,2,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	Keys           []string               `protobuf:"bytes,3,rep,name=keys,proto3" json:"keys,omitempty"` // Empty means get all
	IncludeExpired bool                   `protobuf:"varint,4,opt,name=include_expired,json=includeExpired,proto3" json:"include_expired,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAttributesRequest) Reset() {
	*x = GetAttributesRequest{}
	mi := &file_attribute_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttributesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttributesRequest) ProtoMessage() {}

func (x *GetAttributesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attribute_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttributesRequest.ProtoReflect.Descriptor instead.
func (*GetAttributesRequest) Descriptor() ([]byte, []int) {
	return file_attribute_proto_rawDescGZIP(), []int{3}
}

func (x *GetAttributesRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *GetAttributesRequest) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *GetAttributesRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *GetAttributesRequest) GetIncludeExpired() bool {
	if x != nil {
		return x.IncludeExpired
	}
	return false
}

// Get Attributes Response
type GetAttributesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Attributes    []*Attribute           `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttributesResponse) Reset() {
	*x = GetAttributesResponse{}
	mi := &file_attribute_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttributesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttributesResponse) ProtoMessage() {}

func (x *GetAttributesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attribute_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttributesResponse.ProtoReflect.Descriptor instead.
func (*GetAttributesResponse) Descriptor() ([]byte, []int) {
	return file_attribute_proto_rawDescGZIP(), []int{4}
}

func (x *GetAttributesResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetAttributesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAttributesResponse) GetAttributes() []*Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// Delete Attributes Request
type DeleteAttributesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectId     string                 `protobuf:"bytes,1,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	SubjectType   string                 `protobuf:"bytes,2,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	Keys          []string               `protobuf:"bytes,3,rep,name=keys,proto3" json:"keys,omitempty"` // Empty means delete all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAttributesRequest) Reset() {
	*x = DeleteAttributesRequest{}
	mi := &file_attribute_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAttributesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAttributesRequest) ProtoMessage() {}

func (x *DeleteAttributesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attribute_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAttributesRequest.ProtoReflect.Descriptor instead.
func (*DeleteAttributesRequest) Descriptor() ([]byte, []int) {
	return file_attribute_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteAttributesRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *DeleteAttributesRequest) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *DeleteAttributesRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

// Delete Attributes Response
type DeleteAttributesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DeletedCount  int32                  `protobuf:"varint,3,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAttributesResponse) Reset() {
	*x = DeleteAttributesResponse{}
	mi := &file_attribute_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAttributesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAttributesResponse) ProtoMessage() {}

func (x *DeleteAttributesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attribute_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAttributesResponse.ProtoReflect.Descriptor instead.
func (*DeleteAttributesResponse) Descriptor() ([]byte, []int) {
	return file_attribute_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteAttributesResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *DeleteAttributesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteAttributesResponse) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

// List Attributes Request
type ListAttributesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubjectType    string                 `protobuf:"bytes,1,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	KeyPrefix      string                 `protobuf:"bytes,3,opt,name=key_prefix,json=keyPrefix,proto3" json:"key_prefix,omitempty"` // Filter by key prefix
	IncludeExpired bool                   `protobuf:"varint,4,opt,name=include_expired,json=includeExpired,proto3" json:"include_expired,omitempty"`
	Page           int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize       int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListAttributesRequest) Reset() {
	*x = ListAttributesRequest{}
	mi := &file_attribute_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttributesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttributesRequest) ProtoMessage() {}

func (x *ListAttributesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attribute_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttributesRequest.ProtoReflect.Descriptor instead.
func (*ListAttributesRequest) Descriptor() ([]byte, []int) {
	return file_attribute_proto_rawDescGZIP(), []int{7}
}

func (x *ListAttributesRequest) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *ListAttributesRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListAttributesRequest) GetKeyPrefix() string {
	if x != nil {
		return x.KeyPrefix
	}
	return ""
}

func (x *ListAttributesRequest) GetIncludeExpired() bool {
	if x != nil {
		return x.IncludeExpired
	}
	return false
}

func (x *ListAttributesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAttributesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// List Attributes Response
type ListAttributesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Attributes    []*Attribute           `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAttributesResponse) Reset() {
	*x = ListAttributesResponse{}
	mi := &file_attribute_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttributesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttributesResponse) ProtoMessage() {}

func (x *ListAttributesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attribute_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttributesResponse.ProtoReflect.Descriptor instead.
func (*ListAttributesResponse) Descriptor() ([]byte, []int) {
	return file_attribute_proto_rawDescGZIP(), []int{8}
}

func (x *ListAttributesResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ListAttributesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListAttributesResponse) GetAttributes() []*Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *ListAttributesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListAttributesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAttributesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Attribute History model
type AttributeHistory struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AttributeId    string                 `protobuf:"bytes,2,opt,name=attribute_id,json=attributeId,proto3" json:"attribute_id,omitempty"`
	SubjectId      string                 `protobuf:"bytes,3,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	SubjectType    string                 `protobuf:"bytes,4,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	Key            string                 `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	OldValue       *structpb.Struct       `protobuf:"bytes,6,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"`
	NewValue       *structpb.Struct       `protobuf:"bytes,7,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
	Action         string                 `protobuf:"bytes,8,opt,name=action,proto3" json:"action,omitempty"` // "SET", "DELETE"
	ChangedById    string                 `protobuf:"bytes,9,opt,name=changed_by_id,json=changedById,proto3" json:"changed_by_id,omitempty"`
	ChangedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=changed_at,json=changedAt,proto3" json:"changed_at,omitempty"`
	OrganizationId string                 `protobuf:"bytes,11,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AttributeHistory) Reset() {
	*x = AttributeHistory{}
	mi := &file_attribute_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeHistory) ProtoMessage() {}

func (x *AttributeHistory) ProtoReflect() protoreflect.Message {
	mi := &file_attribute_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeHistory.ProtoReflect.Descriptor instead.
func (*AttributeHistory) Descriptor() ([]byte, []int) {
	return file_attribute_proto_rawDescGZIP(), []int{9}
}

func (x *AttributeHistory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AttributeHistory) GetAttributeId() string {
	if x != nil {
		return x.AttributeId
	}
	return ""
}

func (x *AttributeHistory) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *AttributeHistory) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *AttributeHistory) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AttributeHistory) GetOldValue() *structpb.Struct {
	if x != nil {
		return x.OldValue
	}
	return nil
}

func (x *AttributeHistory) GetNewValue() *structpb.Struct {
	if x != nil {
		return x.NewValue
	}
	return nil
}

func (x *AttributeHistory) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AttributeHistory) GetChangedById() string {
	if x != nil {
		return x.ChangedById
	}
	return ""
}

func (x *AttributeHistory) GetChangedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ChangedAt
	}
	return nil
}

func (x *AttributeHistory) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

// Get Attribute History Request
type GetAttributeHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectId     string                 `protobuf:"bytes,1,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	SubjectType   string                 `protobuf:"bytes,2,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Page          int32                  `protobuf:"varint,6,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,7,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttributeHistoryRequest) Reset() {
	*x = GetAttributeHistoryRequest{}
	mi := &file_attribute_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttributeHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttributeHistoryRequest) ProtoMessage() {}

func (x *GetAttributeHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attribute_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttributeHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetAttributeHistoryRequest) Descriptor() ([]byte, []int) {
	return file_attribute_proto_rawDescGZIP(), []int{10}
}

func (x *GetAttributeHistoryRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *GetAttributeHistoryRequest) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *GetAttributeHistoryRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetAttributeHistoryRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetAttributeHistoryRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *GetAttributeHistoryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAttributeHistoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Get Attribute History Response
type GetAttributeHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	History       []*AttributeHistory    `protobuf:"bytes,3,rep,name=history,proto3" json:"history,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttributeHistoryResponse) Reset() {
	*x = GetAttributeHistoryResponse{}
	mi := &file_attribute_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttributeHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttributeHistoryResponse) ProtoMessage() {}

func (x *GetAttributeHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attribute_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttributeHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetAttributeHistoryResponse) Descriptor() ([]byte, []int) {
	return file_attribute_proto_rawDescGZIP(), []int{11}
}

func (x *GetAttributeHistoryResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetAttributeHistoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAttributeHistoryResponse) GetHistory() []*AttributeHistory {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *GetAttributeHistoryResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetAttributeHistoryResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAttributeHistoryResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Bulk Set Attributes Request
type BulkSetAttributesRequest struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	Subjects      []*BulkSetAttributesRequest_AttributeSubject `protobuf:"bytes,1,rep,name=subjects,proto3" json:"subjects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkSetAttributesRequest) Reset() {
	*x = BulkSetAttributesRequest{}
	mi := &file_attribute_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkSetAttributesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkSetAttributesRequest) ProtoMessage() {}

func (x *BulkSetAttributesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attribute_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkSetAttributesRequest.ProtoReflect.Descriptor instead.
func (*BulkSetAttributesRequest) Descriptor() ([]byte, []int) {
	return file_attribute_proto_rawDescGZIP(), []int{12}
}

func (x *BulkSetAttributesRequest) GetSubjects() []*BulkSetAttributesRequest_AttributeSubject {
	if x != nil {
		return x.Subjects
	}
	return nil
}

// Bulk Set Attributes Response
type BulkSetAttributesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StatusCode     int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SuccessCount   int32                  `protobuf:"varint,3,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailedSubjects []string               `protobuf:"bytes,4,rep,name=failed_subjects,json=failedSubjects,proto3" json:"failed_subjects,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BulkSetAttributesResponse) Reset() {
	*x = BulkSetAttributesResponse{}
	mi := &file_attribute_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkSetAttributesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkSetAttributesResponse) ProtoMessage() {}

func (x *BulkSetAttributesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attribute_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkSetAttributesResponse.ProtoReflect.Descriptor instead.
func (*BulkSetAttributesResponse) Descriptor() ([]byte, []int) {
	return file_attribute_proto_rawDescGZIP(), []int{13}
}

func (x *BulkSetAttributesResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *BulkSetAttributesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BulkSetAttributesResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *BulkSetAttributesResponse) GetFailedSubjects() []string {
	if x != nil {
		return x.FailedSubjects
	}
	return nil
}

// Search Attributes Request
type SearchAttributesRequest struct {
	state           protoimpl.MessageState     `protogen:"open.v1"`
	SubjectType     string                     `protobuf:"bytes,1,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	MatchAttributes map[string]*structpb.Value `protobuf:"bytes,2,rep,name=match_attributes,json=matchAttributes,proto3" json:"match_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Find subjects with these attributes
	OrganizationId  string                     `protobuf:"bytes,3,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Page            int32                      `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize        int32                      `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchAttributesRequest) Reset() {
	*x = SearchAttributesRequest{}
	mi := &file_attribute_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAttributesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAttributesRequest) ProtoMessage() {}

func (x *SearchAttributesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attribute_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAttributesRequest.ProtoReflect.Descriptor instead.
func (*SearchAttributesRequest) Descriptor() ([]byte, []int) {
	return file_attribute_proto_rawDescGZIP(), []int{14}
}

func (x *SearchAttributesRequest) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *SearchAttributesRequest) GetMatchAttributes() map[string]*structpb.Value {
	if x != nil {
		return x.MatchAttributes
	}
	return nil
}

func (x *SearchAttributesRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *SearchAttributesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchAttributesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Search Attributes Response
type SearchAttributesResponse struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	StatusCode    int32                                        `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Subjects      []*SearchAttributesResponse_AttributeSubject `protobuf:"bytes,3,rep,name=subjects,proto3" json:"subjects,omitempty"`
	TotalCount    int32                                        `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                                        `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                                        `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchAttributesResponse) Reset() {
	*x = SearchAttributesResponse{}
	mi := &file_attribute_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAttributesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAttributesResponse) ProtoMessage() {}

func (x *SearchAttributesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attribute_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAttributesResponse.ProtoReflect.Descriptor instead.
func (*SearchAttributesResponse) Descriptor() ([]byte, []int) {
	return file_attribute_proto_rawDescGZIP(), []int{15}
}

func (x *SearchAttributesResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *SearchAttributesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SearchAttributesResponse) GetSubjects() []*SearchAttributesResponse_AttributeSubject {
	if x != nil {
		return x.Subjects
	}
	return nil
}

func (x *SearchAttributesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *SearchAttributesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchAttributesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type BulkSetAttributesRequest_AttributeSubject struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	SubjectId     string                     `protobuf:"bytes,1,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	SubjectType   string                     `protobuf:"bytes,2,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	Attributes    map[string]*structpb.Value `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExpiresAt     *timestamppb.Timestamp     `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkSetAttributesRequest_AttributeSubject) Reset() {
	*x = BulkSetAttributesRequest_AttributeSubject{}
	mi := &file_attribute_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkSetAttributesRequest_AttributeSubject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkSetAttributesRequest_AttributeSubject) ProtoMessage() {}

func (x *BulkSetAttributesRequest_AttributeSubject) ProtoReflect() protoreflect.Message {
	mi := &file_attribute_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkSetAttributesRequest_AttributeSubject.ProtoReflect.Descriptor instead.
func (*BulkSetAttributesRequest_AttributeSubject) Descriptor() ([]byte, []int) {
	return file_attribute_proto_rawDescGZIP(), []int{12, 0}
}

func (x *BulkSetAttributesRequest_AttributeSubject) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *BulkSetAttributesRequest_AttributeSubject) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *BulkSetAttributesRequest_AttributeSubject) GetAttributes() map[string]*structpb.Value {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *BulkSetAttributesRequest_AttributeSubject) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type SearchAttributesResponse_AttributeSubject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectId     string                 `protobuf:"bytes,1,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	SubjectType   string                 `protobuf:"bytes,2,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	Attributes    []*Attribute           `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchAttributesResponse_AttributeSubject) Reset() {
	*x = SearchAttributesResponse_AttributeSubject{}
	mi := &file_attribute_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAttributesResponse_AttributeSubject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAttributesResponse_AttributeSubject) ProtoMessage() {}

func (x *SearchAttributesResponse_AttributeSubject) ProtoReflect() protoreflect.Message {
	mi := &file_attribute_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAttributesResponse_AttributeSubject.ProtoReflect.Descriptor instead.
func (*SearchAttributesResponse_AttributeSubject) Descriptor() ([]byte, []int) {
	return file_attribute_proto_rawDescGZIP(), []int{15, 0}
}

func (x *SearchAttributesResponse_AttributeSubject) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *SearchAttributesResponse_AttributeSubject) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *SearchAttributesResponse_AttributeSubject) GetAttributes() []*Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_attribute_proto protoreflect.FileDescriptor

const file_attribute_proto_rawDesc = "" +
	"\n" +
	"\x0fattribute.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xe6\x03\n" +
	"\tAttribute\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\x12!\n" +
	"\fsubject_type\x18\x03 \x01(\tR\vsubjectType\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x05value\x12'\n" +
	"\x0forganization_id\x18\x06 \x01(\tR\x0eorganizationId\x129\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1b\n" +
	"\tis_active\x18\b \x01(\bR\bisActive\x12\x1a\n" +
	"\tset_by_id\x18\t \x01(\tR\asetById\x123\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xdd\x02\n" +
	"\x14SetAttributesRequest\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x01 \x01(\tR\tsubjectId\x12!\n" +
	"\fsubject_type\x18\x02 \x01(\tR\vsubjectType\x12H\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2(.pb.SetAttributesRequest.AttributesEntryR\n" +
	"attributes\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12'\n" +
	"\x0forganization_id\x18\x05 \x01(\tR\x0eorganizationId\x1aU\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"\x81\x01\n" +
	"\x15SetAttributesResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2\r.pb.AttributeR\n" +
	"attributes\"\x95\x01\n" +
	"\x14GetAttributesRequest\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x01 \x01(\tR\tsubjectId\x12!\n" +
	"\fsubject_type\x18\x02 \x01(\tR\vsubjectType\x12\x12\n" +
	"\x04keys\x18\x03 \x03(\tR\x04keys\x12'\n" +
	"\x0finclude_expired\x18\x04 \x01(\bR\x0eincludeExpired\"\x81\x01\n" +
	"\x15GetAttributesResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2\r.pb.AttributeR\n" +
	"attributes\"o\n" +
	"\x17DeleteAttributesRequest\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x01 \x01(\tR\tsubjectId\x12!\n" +
	"\fsubject_type\x18\x02 \x01(\tR\vsubjectType\x12\x12\n" +
	"\x04keys\x18\x03 \x03(\tR\x04keys\"z\n" +
	"\x18DeleteAttributesResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rdeleted_count\x18\x03 \x01(\x05R\fdeletedCount\"\xdc\x01\n" +
	"\x15ListAttributesRequest\x12!\n" +
	"\fsubject_type\x18\x01 \x01(\tR\vsubjectType\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"key_prefix\x18\x03 \x01(\tR\tkeyPrefix\x12'\n" +
	"\x0finclude_expired\x18\x04 \x01(\bR\x0eincludeExpired\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\"\xd4\x01\n" +
	"\x16ListAttributesResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2\r.pb.AttributeR\n" +
	"attributes\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\"\xa5\x03\n" +
	"\x10AttributeHistory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fattribute_id\x18\x02 \x01(\tR\vattributeId\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x03 \x01(\tR\tsubjectId\x12!\n" +
	"\fsubject_type\x18\x04 \x01(\tR\vsubjectType\x12\x10\n" +
	"\x03key\x18\x05 \x01(\tR\x03key\x124\n" +
	"\told_value\x18\x06 \x01(\v2\x17.google.protobuf.StructR\boldValue\x124\n" +
	"\tnew_value\x18\a \x01(\v2\x17.google.protobuf.StructR\bnewValue\x12\x16\n" +
	"\x06action\x18\b \x01(\tR\x06action\x12\"\n" +
	"\rchanged_by_id\x18\t \x01(\tR\vchangedById\x129\n" +
	"\n" +
	"changed_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tchangedAt\x12'\n" +
	"\x0forganization_id\x18\v \x01(\tR\x0eorganizationId\"\x93\x02\n" +
	"\x1aGetAttributeHistoryRequest\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x01 \x01(\tR\tsubjectId\x12!\n" +
	"\fsubject_type\x18\x02 \x01(\tR\vsubjectType\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x12\n" +
	"\x04page\x18\x06 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\a \x01(\x05R\bpageSize\"\xda\x01\n" +
	"\x1bGetAttributeHistoryResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\ahistory\x18\x03 \x03(\v2\x14.pb.AttributeHistoryR\ahistory\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\"\xad\x03\n" +
	"\x18BulkSetAttributesRequest\x12I\n" +
	"\bsubjects\x18\x01 \x03(\v2-.pb.BulkSetAttributesRequest.AttributeSubjectR\bsubjects\x1a\xc5\x02\n" +
	"\x10AttributeSubject\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x01 \x01(\tR\tsubjectId\x12!\n" +
	"\fsubject_type\x18\x02 \x01(\tR\vsubjectType\x12]\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2=.pb.BulkSetAttributesRequest.AttributeSubject.AttributesEntryR\n" +
	"attributes\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x1aU\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"\xa4\x01\n" +
	"\x19BulkSetAttributesResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rsuccess_count\x18\x03 \x01(\x05R\fsuccessCount\x12'\n" +
	"\x0ffailed_subjects\x18\x04 \x03(\tR\x0efailedSubjects\"\xcf\x02\n" +
	"\x17SearchAttributesRequest\x12!\n" +
	"\fsubject_type\x18\x01 \x01(\tR\vsubjectType\x12[\n" +
	"\x10match_attributes\x18\x02 \x03(\v20.pb.SearchAttributesRequest.MatchAttributesEntryR\x0fmatchAttributes\x12'\n" +
	"\x0forganization_id\x18\x03 \x01(\tR\x0eorganizationId\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\x1aZ\n" +
	"\x14MatchAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"\xf8\x02\n" +
	"\x18SearchAttributesResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12I\n" +
	"\bsubjects\x18\x03 \x03(\v2-.pb.SearchAttributesResponse.AttributeSubjectR\bsubjects\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\x1a\x83\x01\n" +
	"\x10AttributeSubject\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x01 \x01(\tR\tsubjectId\x12!\n" +
	"\fsubject_type\x18\x02 \x01(\tR\vsubjectType\x12-\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2\r.pb.AttributeR\n" +
	"attributes2\xaf\x04\n" +
	"\x10AttributeService\x12D\n" +
	"\rSetAttributes\x12\x18.pb.SetAttributesRequest\x1a\x19.pb.SetAttributesResponse\x12D\n" +
	"\rGetAttributes\x12\x18.pb.GetAttributesRequest\x1a\x19.pb.GetAttributesResponse\x12M\n" +
	"\x10DeleteAttributes\x12\x1b.pb.DeleteAttributesRequest\x1a\x1c.pb.DeleteAttributesResponse\x12G\n" +
	"\x0eListAttributes\x12\x19.pb.ListAttributesRequest\x1a\x1a.pb.ListAttributesResponse\x12V\n" +
	"\x13GetAttributeHistory\x12\x1e.pb.GetAttributeHistoryRequest\x1a\x1f.pb.GetAttributeHistoryResponse\x12P\n" +
	"\x11BulkSetAttributes\x12\x1c.pb.BulkSetAttributesRequest\x1a\x1d.pb.BulkSetAttributesResponse\x12M\n" +
	"\x10SearchAttributes\x12\x1b.pb.SearchAttributesRequest\x1a\x1c.pb.SearchAttributesResponseB/Z-github.com/Kisanlink/farmers-module/pkg/protob\x06proto3"

var (
	file_attribute_proto_rawDescOnce sync.Once
	file_attribute_proto_rawDescData []byte
)

func file_attribute_proto_rawDescGZIP() []byte {
	file_attribute_proto_rawDescOnce.Do(func() {
		file_attribute_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_attribute_proto_rawDesc), len(file_attribute_proto_rawDesc)))
	})
	return file_attribute_proto_rawDescData
}

var file_attribute_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_attribute_proto_goTypes = []any{
	(*Attribute)(nil),                                 // 0: pb.Attribute
	(*SetAttributesRequest)(nil),                      // 1: pb.SetAttributesRequest
	(*SetAttributesResponse)(nil),                     // 2: pb.SetAttributesResponse
	(*GetAttributesRequest)(nil),                      // 3: pb.GetAttributesRequest
	(*GetAttributesResponse)(nil),                     // 4: pb.GetAttributesResponse
	(*DeleteAttributesRequest)(nil),                   // 5: pb.DeleteAttributesRequest
	(*DeleteAttributesResponse)(nil),                  // 6: pb.DeleteAttributesResponse
	(*ListAttributesRequest)(nil),                     // 7: pb.ListAttributesRequest
	(*ListAttributesResponse)(nil),                    // 8: pb.ListAttributesResponse
	(*AttributeHistory)(nil),                          // 9: pb.AttributeHistory
	(*GetAttributeHistoryRequest)(nil),                // 10: pb.GetAttributeHistoryRequest
	(*GetAttributeHistoryResponse)(nil),               // 11: pb.GetAttributeHistoryResponse
	(*BulkSetAttributesRequest)(nil),                  // 12: pb.BulkSetAttributesRequest
	(*BulkSetAttributesResponse)(nil),                 // 13: pb.BulkSetAttributesResponse
	(*SearchAttributesRequest)(nil),                   // 14: pb.SearchAttributesRequest
	(*SearchAttributesResponse)(nil),                  // 15: pb.SearchAttributesResponse
	nil,                                               // 16: pb.SetAttributesRequest.AttributesEntry
	(*BulkSetAttributesRequest_AttributeSubject)(nil), // 17: pb.BulkSetAttributesRequest.AttributeSubject
	nil, // 18: pb.BulkSetAttributesRequest.AttributeSubject.AttributesEntry
	nil, // 19: pb.SearchAttributesRequest.MatchAttributesEntry
	(*SearchAttributesResponse_AttributeSubject)(nil), // 20: pb.SearchAttributesResponse.AttributeSubject
	(*structpb.Struct)(nil),                           // 21: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),                     // 22: google.protobuf.Timestamp
	(*structpb.Value)(nil),                            // 23: google.protobuf.Value
}
var file_attribute_proto_depIdxs = []int32{
	21, // 0: pb.Attribute.value:type_name -> google.protobuf.Struct
	22, // 1: pb.Attribute.expires_at:type_name -> google.protobuf.Timestamp
	21, // 2: pb.Attribute.metadata:type_name -> google.protobuf.Struct
	22, // 3: pb.Attribute.created_at:type_name -> google.protobuf.Timestamp
	22, // 4: pb.Attribute.updated_at:type_name -> google.protobuf.Timestamp
	16, // 5: pb.SetAttributesRequest.attributes:type_name -> pb.SetAttributesRequest.AttributesEntry
	22, // 6: pb.SetAttributesRequest.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 7: pb.SetAttributesResponse.attributes:type_name -> pb.Attribute
	0,  // 8: pb.GetAttributesResponse.attributes:type_name -> pb.Attribute
	0,  // 9: pb.ListAttributesResponse.attributes:type_name -> pb.Attribute
	21, // 10: pb.AttributeHistory.old_value:type_name -> google.protobuf.Struct
	21, // 11: pb.AttributeHistory.new_value:type_name -> google.protobuf.Struct
	22, // 12: pb.AttributeHistory.changed_at:type_name -> google.protobuf.Timestamp
	22, // 13: pb.GetAttributeHistoryRequest.start_time:type_name -> google.protobuf.Timestamp
	22, // 14: pb.GetAttributeHistoryRequest.end_time:type_name -> google.protobuf.Timestamp
	9,  // 15: pb.GetAttributeHistoryResponse.history:type_name -> pb.AttributeHistory
	17, // 16: pb.BulkSetAttributesRequest.subjects:type_name -> pb.BulkSetAttributesRequest.AttributeSubject
	19, // 17: pb.SearchAttributesRequest.match_attributes:type_name -> pb.SearchAttributesRequest.MatchAttributesEntry
	20, // 18: pb.SearchAttributesResponse.subjects:type_name -> pb.SearchAttributesResponse.AttributeSubject
	23, // 19: pb.SetAttributesRequest.AttributesEntry.value:type_name -> google.protobuf.Value
	18, // 20: pb.BulkSetAttributesRequest.AttributeSubject.attributes:type_name -> pb.BulkSetAttributesRequest.AttributeSubject.AttributesEntry
	22, // 21: pb.BulkSetAttributesRequest.AttributeSubject.expires_at:type_name -> google.protobuf.Timestamp
	23, // 22: pb.BulkSetAttributesRequest.AttributeSubject.AttributesEntry.value:type_name -> google.protobuf.Value
	23, // 23: pb.SearchAttributesRequest.MatchAttributesEntry.value:type_name -> google.protobuf.Value
	0,  // 24: pb.SearchAttributesResponse.AttributeSubject.attributes:type_name -> pb.Attribute
	1,  // 25: pb.AttributeService.SetAttributes:input_type -> pb.SetAttributesRequest
	3,  // 26: pb.AttributeService.GetAttributes:input_type -> pb.GetAttributesRequest
	5,  // 27: pb.AttributeService.DeleteAttributes:input_type -> pb.DeleteAttributesRequest
	7,  // 28: pb.AttributeService.ListAttributes:input_type -> pb.ListAttributesRequest
	10, // 29: pb.AttributeService.GetAttributeHistory:input_type -> pb.GetAttributeHistoryRequest
	12, // 30: pb.AttributeService.BulkSetAttributes:input_type -> pb.BulkSetAttributesRequest
	14, // 31: pb.AttributeService.SearchAttributes:input_type -> pb.SearchAttributesRequest
	2,  // 32: pb.AttributeService.SetAttributes:output_type -> pb.SetAttributesResponse
	4,  // 33: pb.AttributeService.GetAttributes:output_type -> pb.GetAttributesResponse
	6,  // 34: pb.AttributeService.DeleteAttributes:output_type -> pb.DeleteAttributesResponse
	8,  // 35: pb.AttributeService.ListAttributes:output_type -> pb.ListAttributesResponse
	11, // 36: pb.AttributeService.GetAttributeHistory:output_type -> pb.GetAttributeHistoryResponse
	13, // 37: pb.AttributeService.BulkSetAttributes:output_type -> pb.BulkSetAttributesResponse
	15, // 38: pb.AttributeService.SearchAttributes:output_type -> pb.SearchAttributesResponse
	32, // [32:39] is the sub-list for method output_type
	25, // [25:32] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_attribute_proto_init() }
func file_attribute_proto_init() {
	if File_attribute_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_attribute_proto_rawDesc), len(file_attribute_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_attribute_proto_goTypes,
		DependencyIndexes: file_attribute_proto_depIdxs,
		MessageInfos:      file_attribute_proto_msgTypes,
	}.Build()
	File_attribute_proto = out.File
	file_attribute_proto_goTypes = nil
	file_attribute_proto_depIdxs = nil
}
