// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: pkg/proto/authz.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Check Request - single authorization check
type CheckRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	PrincipalId  string                 `protobuf:"bytes,1,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"`    // User or Service ID
	ResourceType string                 `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"` // e.g., "aaa/table", "aaa/resource"
	ResourceId   string                 `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`       // Specific resource instance
	Action       string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`                                 // e.g., "view", "edit", "delete"
	// Context for caveat evaluation
	Attributes       *structpb.Struct       `protobuf:"bytes,5,opt,name=attributes,proto3" json:"attributes,omitempty"`                                     // Principal attributes
	RequestedColumns []string               `protobuf:"bytes,6,rep,name=requested_columns,json=requestedColumns,proto3" json:"requested_columns,omitempty"` // For column-level checks
	CheckTime        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=check_time,json=checkTime,proto3" json:"check_time,omitempty"`                      // Time for time-based caveats
	// Consistency options
	ConsistencyToken string `protobuf:"bytes,8,opt,name=consistency_token,json=consistencyToken,proto3" json:"consistency_token,omitempty"` // Use specific consistency point
	UseStrict        bool   `protobuf:"varint,9,opt,name=use_strict,json=useStrict,proto3" json:"use_strict,omitempty"`                     // Force strict consistency
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_pkg_proto_authz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_authz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_authz_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRequest) GetPrincipalId() string {
	if x != nil {
		return x.PrincipalId
	}
	return ""
}

func (x *CheckRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *CheckRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *CheckRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CheckRequest) GetAttributes() *structpb.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *CheckRequest) GetRequestedColumns() []string {
	if x != nil {
		return x.RequestedColumns
	}
	return nil
}

func (x *CheckRequest) GetCheckTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckTime
	}
	return nil
}

func (x *CheckRequest) GetConsistencyToken() string {
	if x != nil {
		return x.ConsistencyToken
	}
	return ""
}

func (x *CheckRequest) GetUseStrict() bool {
	if x != nil {
		return x.UseStrict
	}
	return false
}

// Check Response
type CheckResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Allowed          bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	DecisionId       string                 `protobuf:"bytes,2,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`                   // Unique ID for this decision
	Reasons          []string               `protobuf:"bytes,3,rep,name=reasons,proto3" json:"reasons,omitempty"`                                           // Human-readable reasons
	ConsistencyToken string                 `protobuf:"bytes,4,opt,name=consistency_token,json=consistencyToken,proto3" json:"consistency_token,omitempty"` // Current consistency point
	// Debug information (optional)
	Debug         *DebugInfo `protobuf:"bytes,5,opt,name=debug,proto3" json:"debug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_pkg_proto_authz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_authz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_authz_proto_rawDescGZIP(), []int{1}
}

func (x *CheckResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckResponse) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *CheckResponse) GetReasons() []string {
	if x != nil {
		return x.Reasons
	}
	return nil
}

func (x *CheckResponse) GetConsistencyToken() string {
	if x != nil {
		return x.ConsistencyToken
	}
	return ""
}

func (x *CheckResponse) GetDebug() *DebugInfo {
	if x != nil {
		return x.Debug
	}
	return nil
}

// Debug information for authorization decisions
type DebugInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TuplePath        []string               `protobuf:"bytes,1,rep,name=tuple_path,json=tuplePath,proto3" json:"tuple_path,omitempty"`                         // SpiceDB tuple path
	Caveats          []*CaveatEvaluation    `protobuf:"bytes,2,rep,name=caveats,proto3" json:"caveats,omitempty"`                                              // Caveat evaluation details
	EvaluationTimeMs int64                  `protobuf:"varint,3,opt,name=evaluation_time_ms,json=evaluationTimeMs,proto3" json:"evaluation_time_ms,omitempty"` // Time taken for evaluation
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DebugInfo) Reset() {
	*x = DebugInfo{}
	mi := &file_pkg_proto_authz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugInfo) ProtoMessage() {}

func (x *DebugInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_authz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugInfo.ProtoReflect.Descriptor instead.
func (*DebugInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_authz_proto_rawDescGZIP(), []int{2}
}

func (x *DebugInfo) GetTuplePath() []string {
	if x != nil {
		return x.TuplePath
	}
	return nil
}

func (x *DebugInfo) GetCaveats() []*CaveatEvaluation {
	if x != nil {
		return x.Caveats
	}
	return nil
}

func (x *DebugInfo) GetEvaluationTimeMs() int64 {
	if x != nil {
		return x.EvaluationTimeMs
	}
	return 0
}

// Caveat evaluation details
type CaveatEvaluation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaveatName    string                 `protobuf:"bytes,1,opt,name=caveat_name,json=caveatName,proto3" json:"caveat_name,omitempty"`
	CaveatContext *structpb.Struct       `protobuf:"bytes,2,opt,name=caveat_context,json=caveatContext,proto3" json:"caveat_context,omitempty"`
	Result        bool                   `protobuf:"varint,3,opt,name=result,proto3" json:"result,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaveatEvaluation) Reset() {
	*x = CaveatEvaluation{}
	mi := &file_pkg_proto_authz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaveatEvaluation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaveatEvaluation) ProtoMessage() {}

func (x *CaveatEvaluation) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_authz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaveatEvaluation.ProtoReflect.Descriptor instead.
func (*CaveatEvaluation) Descriptor() ([]byte, []int) {
	return file_pkg_proto_authz_proto_rawDescGZIP(), []int{3}
}

func (x *CaveatEvaluation) GetCaveatName() string {
	if x != nil {
		return x.CaveatName
	}
	return ""
}

func (x *CaveatEvaluation) GetCaveatContext() *structpb.Struct {
	if x != nil {
		return x.CaveatContext
	}
	return nil
}

func (x *CaveatEvaluation) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *CaveatEvaluation) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Batch Check Request - multiple authorization checks
type BatchCheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Items []*CheckItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// Shared context for all checks
	SharedAttributes *structpb.Struct       `protobuf:"bytes,2,opt,name=shared_attributes,json=sharedAttributes,proto3" json:"shared_attributes,omitempty"`
	CheckTime        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=check_time,json=checkTime,proto3" json:"check_time,omitempty"`
	// Consistency options
	ConsistencyToken string `protobuf:"bytes,4,opt,name=consistency_token,json=consistencyToken,proto3" json:"consistency_token,omitempty"`
	UseStrict        bool   `protobuf:"varint,5,opt,name=use_strict,json=useStrict,proto3" json:"use_strict,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BatchCheckRequest) Reset() {
	*x = BatchCheckRequest{}
	mi := &file_pkg_proto_authz_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCheckRequest) ProtoMessage() {}

func (x *BatchCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_authz_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCheckRequest.ProtoReflect.Descriptor instead.
func (*BatchCheckRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_authz_proto_rawDescGZIP(), []int{4}
}

func (x *BatchCheckRequest) GetItems() []*CheckItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *BatchCheckRequest) GetSharedAttributes() *structpb.Struct {
	if x != nil {
		return x.SharedAttributes
	}
	return nil
}

func (x *BatchCheckRequest) GetCheckTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckTime
	}
	return nil
}

func (x *BatchCheckRequest) GetConsistencyToken() string {
	if x != nil {
		return x.ConsistencyToken
	}
	return ""
}

func (x *BatchCheckRequest) GetUseStrict() bool {
	if x != nil {
		return x.UseStrict
	}
	return false
}

// Individual check item in batch
type CheckItem struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestId        string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // Client-provided ID for correlation
	PrincipalId      string                 `protobuf:"bytes,2,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"`
	ResourceType     string                 `protobuf:"bytes,3,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceId       string                 `protobuf:"bytes,4,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Action           string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	Attributes       *structpb.Struct       `protobuf:"bytes,6,opt,name=attributes,proto3" json:"attributes,omitempty"` // Override shared attributes
	RequestedColumns []string               `protobuf:"bytes,7,rep,name=requested_columns,json=requestedColumns,proto3" json:"requested_columns,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CheckItem) Reset() {
	*x = CheckItem{}
	mi := &file_pkg_proto_authz_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckItem) ProtoMessage() {}

func (x *CheckItem) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_authz_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckItem.ProtoReflect.Descriptor instead.
func (*CheckItem) Descriptor() ([]byte, []int) {
	return file_pkg_proto_authz_proto_rawDescGZIP(), []int{5}
}

func (x *CheckItem) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CheckItem) GetPrincipalId() string {
	if x != nil {
		return x.PrincipalId
	}
	return ""
}

func (x *CheckItem) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *CheckItem) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *CheckItem) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CheckItem) GetAttributes() *structpb.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *CheckItem) GetRequestedColumns() []string {
	if x != nil {
		return x.RequestedColumns
	}
	return nil
}

// Batch Check Response
type BatchCheckResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Results          []*CheckResult         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	ConsistencyToken string                 `protobuf:"bytes,2,opt,name=consistency_token,json=consistencyToken,proto3" json:"consistency_token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BatchCheckResponse) Reset() {
	*x = BatchCheckResponse{}
	mi := &file_pkg_proto_authz_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCheckResponse) ProtoMessage() {}

func (x *BatchCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_authz_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCheckResponse.ProtoReflect.Descriptor instead.
func (*BatchCheckResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_authz_proto_rawDescGZIP(), []int{6}
}

func (x *BatchCheckResponse) GetResults() []*CheckResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *BatchCheckResponse) GetConsistencyToken() string {
	if x != nil {
		return x.ConsistencyToken
	}
	return ""
}

// Individual check result in batch
type CheckResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Allowed       bool                   `protobuf:"varint,2,opt,name=allowed,proto3" json:"allowed,omitempty"`
	DecisionId    string                 `protobuf:"bytes,3,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	Reasons       []string               `protobuf:"bytes,4,rep,name=reasons,proto3" json:"reasons,omitempty"`
	Debug         *DebugInfo             `protobuf:"bytes,5,opt,name=debug,proto3" json:"debug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResult) Reset() {
	*x = CheckResult{}
	mi := &file_pkg_proto_authz_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResult) ProtoMessage() {}

func (x *CheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_authz_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResult.ProtoReflect.Descriptor instead.
func (*CheckResult) Descriptor() ([]byte, []int) {
	return file_pkg_proto_authz_proto_rawDescGZIP(), []int{7}
}

func (x *CheckResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CheckResult) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckResult) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *CheckResult) GetReasons() []string {
	if x != nil {
		return x.Reasons
	}
	return nil
}

func (x *CheckResult) GetDebug() *DebugInfo {
	if x != nil {
		return x.Debug
	}
	return nil
}

// Lookup Resources Request - find resources user can access
type LookupResourcesRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	PrincipalId  string                 `protobuf:"bytes,1,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"`
	ResourceType string                 `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	Action       string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	// Filters
	ParentResourceId string `protobuf:"bytes,4,opt,name=parent_resource_id,json=parentResourceId,proto3" json:"parent_resource_id,omitempty"`
	OrganizationId   string `protobuf:"bytes,5,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	// Context
	Attributes *structpb.Struct       `protobuf:"bytes,6,opt,name=attributes,proto3" json:"attributes,omitempty"`
	CheckTime  *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=check_time,json=checkTime,proto3" json:"check_time,omitempty"`
	// Pagination
	Page              int32  `protobuf:"varint,8,opt,name=page,proto3" json:"page,omitempty"`
	PageSize          int32  `protobuf:"varint,9,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	ContinuationToken string `protobuf:"bytes,10,opt,name=continuation_token,json=continuationToken,proto3" json:"continuation_token,omitempty"`
	// Consistency
	ConsistencyToken string `protobuf:"bytes,11,opt,name=consistency_token,json=consistencyToken,proto3" json:"consistency_token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LookupResourcesRequest) Reset() {
	*x = LookupResourcesRequest{}
	mi := &file_pkg_proto_authz_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupResourcesRequest) ProtoMessage() {}

func (x *LookupResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_authz_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupResourcesRequest.ProtoReflect.Descriptor instead.
func (*LookupResourcesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_authz_proto_rawDescGZIP(), []int{8}
}

func (x *LookupResourcesRequest) GetPrincipalId() string {
	if x != nil {
		return x.PrincipalId
	}
	return ""
}

func (x *LookupResourcesRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *LookupResourcesRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *LookupResourcesRequest) GetParentResourceId() string {
	if x != nil {
		return x.ParentResourceId
	}
	return ""
}

func (x *LookupResourcesRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *LookupResourcesRequest) GetAttributes() *structpb.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *LookupResourcesRequest) GetCheckTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckTime
	}
	return nil
}

func (x *LookupResourcesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *LookupResourcesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *LookupResourcesRequest) GetContinuationToken() string {
	if x != nil {
		return x.ContinuationToken
	}
	return ""
}

func (x *LookupResourcesRequest) GetConsistencyToken() string {
	if x != nil {
		return x.ConsistencyToken
	}
	return ""
}

// Lookup Resources Response
type LookupResourcesResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Resources         []*ResourceAccess      `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	ContinuationToken string                 `protobuf:"bytes,2,opt,name=continuation_token,json=continuationToken,proto3" json:"continuation_token,omitempty"`
	ConsistencyToken  string                 `protobuf:"bytes,3,opt,name=consistency_token,json=consistencyToken,proto3" json:"consistency_token,omitempty"`
	TotalCount        int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LookupResourcesResponse) Reset() {
	*x = LookupResourcesResponse{}
	mi := &file_pkg_proto_authz_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupResourcesResponse) ProtoMessage() {}

func (x *LookupResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_authz_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupResourcesResponse.ProtoReflect.Descriptor instead.
func (*LookupResourcesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_authz_proto_rawDescGZIP(), []int{9}
}

func (x *LookupResourcesResponse) GetResources() []*ResourceAccess {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *LookupResourcesResponse) GetContinuationToken() string {
	if x != nil {
		return x.ContinuationToken
	}
	return ""
}

func (x *LookupResourcesResponse) GetConsistencyToken() string {
	if x != nil {
		return x.ConsistencyToken
	}
	return ""
}

func (x *LookupResourcesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// Resource access information
type ResourceAccess struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ResourceId     string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ResourceType   string                 `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	AllowedActions []string               `protobuf:"bytes,3,rep,name=allowed_actions,json=allowedActions,proto3" json:"allowed_actions,omitempty"`
	Metadata       *structpb.Struct       `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"` // Resource metadata
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResourceAccess) Reset() {
	*x = ResourceAccess{}
	mi := &file_pkg_proto_authz_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceAccess) ProtoMessage() {}

func (x *ResourceAccess) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_authz_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceAccess.ProtoReflect.Descriptor instead.
func (*ResourceAccess) Descriptor() ([]byte, []int) {
	return file_pkg_proto_authz_proto_rawDescGZIP(), []int{10}
}

func (x *ResourceAccess) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *ResourceAccess) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *ResourceAccess) GetAllowedActions() []string {
	if x != nil {
		return x.AllowedActions
	}
	return nil
}

func (x *ResourceAccess) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Check Columns Request - column-level authorization
type CheckColumnsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PrincipalId      string                 `protobuf:"bytes,1,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"`
	TableName        string                 `protobuf:"bytes,2,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	ResourceId       string                 `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"` // Specific table instance
	RequestedColumns []string               `protobuf:"bytes,4,rep,name=requested_columns,json=requestedColumns,proto3" json:"requested_columns,omitempty"`
	Action           string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"` // "read" or "write"
	// Context
	Attributes *structpb.Struct       `protobuf:"bytes,6,opt,name=attributes,proto3" json:"attributes,omitempty"`
	CheckTime  *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=check_time,json=checkTime,proto3" json:"check_time,omitempty"`
	// Consistency
	ConsistencyToken string `protobuf:"bytes,8,opt,name=consistency_token,json=consistencyToken,proto3" json:"consistency_token,omitempty"`
	UseStrict        bool   `protobuf:"varint,9,opt,name=use_strict,json=useStrict,proto3" json:"use_strict,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CheckColumnsRequest) Reset() {
	*x = CheckColumnsRequest{}
	mi := &file_pkg_proto_authz_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckColumnsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckColumnsRequest) ProtoMessage() {}

func (x *CheckColumnsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_authz_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckColumnsRequest.ProtoReflect.Descriptor instead.
func (*CheckColumnsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_authz_proto_rawDescGZIP(), []int{11}
}

func (x *CheckColumnsRequest) GetPrincipalId() string {
	if x != nil {
		return x.PrincipalId
	}
	return ""
}

func (x *CheckColumnsRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *CheckColumnsRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *CheckColumnsRequest) GetRequestedColumns() []string {
	if x != nil {
		return x.RequestedColumns
	}
	return nil
}

func (x *CheckColumnsRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CheckColumnsRequest) GetAttributes() *structpb.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *CheckColumnsRequest) GetCheckTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckTime
	}
	return nil
}

func (x *CheckColumnsRequest) GetConsistencyToken() string {
	if x != nil {
		return x.ConsistencyToken
	}
	return ""
}

func (x *CheckColumnsRequest) GetUseStrict() bool {
	if x != nil {
		return x.UseStrict
	}
	return false
}

// Check Columns Response
type CheckColumnsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Allowed          bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`                                    // Overall decision
	AllowedColumns   []string               `protobuf:"bytes,2,rep,name=allowed_columns,json=allowedColumns,proto3" json:"allowed_columns,omitempty"` // Subset of requested columns allowed
	DeniedColumns    []string               `protobuf:"bytes,3,rep,name=denied_columns,json=deniedColumns,proto3" json:"denied_columns,omitempty"`    // Columns explicitly denied
	ColumnGroups     []string               `protobuf:"bytes,4,rep,name=column_groups,json=columnGroups,proto3" json:"column_groups,omitempty"`       // Column groups user has access to
	DecisionId       string                 `protobuf:"bytes,5,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	ConsistencyToken string                 `protobuf:"bytes,6,opt,name=consistency_token,json=consistencyToken,proto3" json:"consistency_token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CheckColumnsResponse) Reset() {
	*x = CheckColumnsResponse{}
	mi := &file_pkg_proto_authz_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckColumnsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckColumnsResponse) ProtoMessage() {}

func (x *CheckColumnsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_authz_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckColumnsResponse.ProtoReflect.Descriptor instead.
func (*CheckColumnsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_authz_proto_rawDescGZIP(), []int{12}
}

func (x *CheckColumnsResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckColumnsResponse) GetAllowedColumns() []string {
	if x != nil {
		return x.AllowedColumns
	}
	return nil
}

func (x *CheckColumnsResponse) GetDeniedColumns() []string {
	if x != nil {
		return x.DeniedColumns
	}
	return nil
}

func (x *CheckColumnsResponse) GetColumnGroups() []string {
	if x != nil {
		return x.ColumnGroups
	}
	return nil
}

func (x *CheckColumnsResponse) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *CheckColumnsResponse) GetConsistencyToken() string {
	if x != nil {
		return x.ConsistencyToken
	}
	return ""
}

// List Allowed Columns Request - get all accessible columns
type ListAllowedColumnsRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	PrincipalId string                 `protobuf:"bytes,1,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"`
	TableName   string                 `protobuf:"bytes,2,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	ResourceId  string                 `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Action      string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	// Context
	Attributes *structpb.Struct       `protobuf:"bytes,5,opt,name=attributes,proto3" json:"attributes,omitempty"`
	CheckTime  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=check_time,json=checkTime,proto3" json:"check_time,omitempty"`
	// Consistency
	ConsistencyToken string `protobuf:"bytes,7,opt,name=consistency_token,json=consistencyToken,proto3" json:"consistency_token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListAllowedColumnsRequest) Reset() {
	*x = ListAllowedColumnsRequest{}
	mi := &file_pkg_proto_authz_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllowedColumnsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllowedColumnsRequest) ProtoMessage() {}

func (x *ListAllowedColumnsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_authz_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllowedColumnsRequest.ProtoReflect.Descriptor instead.
func (*ListAllowedColumnsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_authz_proto_rawDescGZIP(), []int{13}
}

func (x *ListAllowedColumnsRequest) GetPrincipalId() string {
	if x != nil {
		return x.PrincipalId
	}
	return ""
}

func (x *ListAllowedColumnsRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *ListAllowedColumnsRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *ListAllowedColumnsRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ListAllowedColumnsRequest) GetAttributes() *structpb.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *ListAllowedColumnsRequest) GetCheckTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckTime
	}
	return nil
}

func (x *ListAllowedColumnsRequest) GetConsistencyToken() string {
	if x != nil {
		return x.ConsistencyToken
	}
	return ""
}

// List Allowed Columns Response
type ListAllowedColumnsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AllowedColumns   []string               `protobuf:"bytes,1,rep,name=allowed_columns,json=allowedColumns,proto3" json:"allowed_columns,omitempty"`
	ColumnGroups     []*ColumnGroupAccess   `protobuf:"bytes,2,rep,name=column_groups,json=columnGroups,proto3" json:"column_groups,omitempty"`
	ConsistencyToken string                 `protobuf:"bytes,3,opt,name=consistency_token,json=consistencyToken,proto3" json:"consistency_token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListAllowedColumnsResponse) Reset() {
	*x = ListAllowedColumnsResponse{}
	mi := &file_pkg_proto_authz_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllowedColumnsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllowedColumnsResponse) ProtoMessage() {}

func (x *ListAllowedColumnsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_authz_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllowedColumnsResponse.ProtoReflect.Descriptor instead.
func (*ListAllowedColumnsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_authz_proto_rawDescGZIP(), []int{14}
}

func (x *ListAllowedColumnsResponse) GetAllowedColumns() []string {
	if x != nil {
		return x.AllowedColumns
	}
	return nil
}

func (x *ListAllowedColumnsResponse) GetColumnGroups() []*ColumnGroupAccess {
	if x != nil {
		return x.ColumnGroups
	}
	return nil
}

func (x *ListAllowedColumnsResponse) GetConsistencyToken() string {
	if x != nil {
		return x.ConsistencyToken
	}
	return ""
}

// Column group access information
type ColumnGroupAccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupName     string                 `protobuf:"bytes,1,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Columns       []string               `protobuf:"bytes,3,rep,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnGroupAccess) Reset() {
	*x = ColumnGroupAccess{}
	mi := &file_pkg_proto_authz_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnGroupAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnGroupAccess) ProtoMessage() {}

func (x *ColumnGroupAccess) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_authz_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnGroupAccess.ProtoReflect.Descriptor instead.
func (*ColumnGroupAccess) Descriptor() ([]byte, []int) {
	return file_pkg_proto_authz_proto_rawDescGZIP(), []int{15}
}

func (x *ColumnGroupAccess) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *ColumnGroupAccess) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ColumnGroupAccess) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

// Explain Request - explain authorization decision
type ExplainRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	PrincipalId  string                 `protobuf:"bytes,1,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"`
	ResourceType string                 `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceId   string                 `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Action       string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	// Context
	Attributes       *structpb.Struct       `protobuf:"bytes,5,opt,name=attributes,proto3" json:"attributes,omitempty"`
	RequestedColumns []string               `protobuf:"bytes,6,rep,name=requested_columns,json=requestedColumns,proto3" json:"requested_columns,omitempty"`
	CheckTime        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=check_time,json=checkTime,proto3" json:"check_time,omitempty"`
	// Options
	IncludeTuplePath   bool `protobuf:"varint,8,opt,name=include_tuple_path,json=includeTuplePath,proto3" json:"include_tuple_path,omitempty"`
	IncludeCaveats     bool `protobuf:"varint,9,opt,name=include_caveats,json=includeCaveats,proto3" json:"include_caveats,omitempty"`
	IncludeDeniedPaths bool `protobuf:"varint,10,opt,name=include_denied_paths,json=includeDeniedPaths,proto3" json:"include_denied_paths,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ExplainRequest) Reset() {
	*x = ExplainRequest{}
	mi := &file_pkg_proto_authz_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainRequest) ProtoMessage() {}

func (x *ExplainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_authz_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainRequest.ProtoReflect.Descriptor instead.
func (*ExplainRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_authz_proto_rawDescGZIP(), []int{16}
}

func (x *ExplainRequest) GetPrincipalId() string {
	if x != nil {
		return x.PrincipalId
	}
	return ""
}

func (x *ExplainRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *ExplainRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *ExplainRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ExplainRequest) GetAttributes() *structpb.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *ExplainRequest) GetRequestedColumns() []string {
	if x != nil {
		return x.RequestedColumns
	}
	return nil
}

func (x *ExplainRequest) GetCheckTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckTime
	}
	return nil
}

func (x *ExplainRequest) GetIncludeTuplePath() bool {
	if x != nil {
		return x.IncludeTuplePath
	}
	return false
}

func (x *ExplainRequest) GetIncludeCaveats() bool {
	if x != nil {
		return x.IncludeCaveats
	}
	return false
}

func (x *ExplainRequest) GetIncludeDeniedPaths() bool {
	if x != nil {
		return x.IncludeDeniedPaths
	}
	return false
}

// Explain Response
type ExplainResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Allowed    bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	DecisionId string                 `protobuf:"bytes,2,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	// Explanation details
	AllowedPaths []*TuplePath        `protobuf:"bytes,3,rep,name=allowed_paths,json=allowedPaths,proto3" json:"allowed_paths,omitempty"` // Paths that grant access
	DeniedPaths  []*TuplePath        `protobuf:"bytes,4,rep,name=denied_paths,json=deniedPaths,proto3" json:"denied_paths,omitempty"`    // Paths that were checked but denied
	Caveats      []*CaveatEvaluation `protobuf:"bytes,5,rep,name=caveats,proto3" json:"caveats,omitempty"`                               // All caveat evaluations
	// Summary
	HumanExplanation string `protobuf:"bytes,6,opt,name=human_explanation,json=humanExplanation,proto3" json:"human_explanation,omitempty"` // Human-readable explanation
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExplainResponse) Reset() {
	*x = ExplainResponse{}
	mi := &file_pkg_proto_authz_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainResponse) ProtoMessage() {}

func (x *ExplainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_authz_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainResponse.ProtoReflect.Descriptor instead.
func (*ExplainResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_authz_proto_rawDescGZIP(), []int{17}
}

func (x *ExplainResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *ExplainResponse) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *ExplainResponse) GetAllowedPaths() []*TuplePath {
	if x != nil {
		return x.AllowedPaths
	}
	return nil
}

func (x *ExplainResponse) GetDeniedPaths() []*TuplePath {
	if x != nil {
		return x.DeniedPaths
	}
	return nil
}

func (x *ExplainResponse) GetCaveats() []*CaveatEvaluation {
	if x != nil {
		return x.Caveats
	}
	return nil
}

func (x *ExplainResponse) GetHumanExplanation() string {
	if x != nil {
		return x.HumanExplanation
	}
	return ""
}

// Tuple path in authorization graph
type TuplePath struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*TupleNode           `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	IsAllowed     bool                   `protobuf:"varint,2,opt,name=is_allowed,json=isAllowed,proto3" json:"is_allowed,omitempty"`
	DeniedReason  string                 `protobuf:"bytes,3,opt,name=denied_reason,json=deniedReason,proto3" json:"denied_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TuplePath) Reset() {
	*x = TuplePath{}
	mi := &file_pkg_proto_authz_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TuplePath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TuplePath) ProtoMessage() {}

func (x *TuplePath) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_authz_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TuplePath.ProtoReflect.Descriptor instead.
func (*TuplePath) Descriptor() ([]byte, []int) {
	return file_pkg_proto_authz_proto_rawDescGZIP(), []int{18}
}

func (x *TuplePath) GetNodes() []*TupleNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *TuplePath) GetIsAllowed() bool {
	if x != nil {
		return x.IsAllowed
	}
	return false
}

func (x *TuplePath) GetDeniedReason() string {
	if x != nil {
		return x.DeniedReason
	}
	return ""
}

// Node in tuple path
type TupleNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectType    string                 `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	ObjectId      string                 `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Relation      string                 `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	SubjectType   string                 `protobuf:"bytes,4,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	SubjectId     string                 `protobuf:"bytes,5,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TupleNode) Reset() {
	*x = TupleNode{}
	mi := &file_pkg_proto_authz_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TupleNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TupleNode) ProtoMessage() {}

func (x *TupleNode) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_authz_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TupleNode.ProtoReflect.Descriptor instead.
func (*TupleNode) Descriptor() ([]byte, []int) {
	return file_pkg_proto_authz_proto_rawDescGZIP(), []int{19}
}

func (x *TupleNode) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *TupleNode) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *TupleNode) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *TupleNode) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *TupleNode) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

var File_pkg_proto_authz_proto protoreflect.FileDescriptor

const file_pkg_proto_authz_proto_rawDesc = "" +
	"\n" +
	"\x15pkg/proto/authz.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xfc\x02\n" +
	"\fCheckRequest\x12!\n" +
	"\fprincipal_id\x18\x01 \x01(\tR\vprincipalId\x12#\n" +
	"\rresource_type\x18\x02 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x127\n" +
	"\n" +
	"attributes\x18\x05 \x01(\v2\x17.google.protobuf.StructR\n" +
	"attributes\x12+\n" +
	"\x11requested_columns\x18\x06 \x03(\tR\x10requestedColumns\x129\n" +
	"\n" +
	"check_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcheckTime\x12+\n" +
	"\x11consistency_token\x18\b \x01(\tR\x10consistencyToken\x12\x1d\n" +
	"\n" +
	"use_strict\x18\t \x01(\bR\tuseStrict\"\xb6\x01\n" +
	"\rCheckResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x1f\n" +
	"\vdecision_id\x18\x02 \x01(\tR\n" +
	"decisionId\x12\x18\n" +
	"\areasons\x18\x03 \x03(\tR\areasons\x12+\n" +
	"\x11consistency_token\x18\x04 \x01(\tR\x10consistencyToken\x12#\n" +
	"\x05debug\x18\x05 \x01(\v2\r.pb.DebugInfoR\x05debug\"\x88\x01\n" +
	"\tDebugInfo\x12\x1d\n" +
	"\n" +
	"tuple_path\x18\x01 \x03(\tR\ttuplePath\x12.\n" +
	"\acaveats\x18\x02 \x03(\v2\x14.pb.CaveatEvaluationR\acaveats\x12,\n" +
	"\x12evaluation_time_ms\x18\x03 \x01(\x03R\x10evaluationTimeMs\"\xa3\x01\n" +
	"\x10CaveatEvaluation\x12\x1f\n" +
	"\vcaveat_name\x18\x01 \x01(\tR\n" +
	"caveatName\x12>\n" +
	"\x0ecaveat_context\x18\x02 \x01(\v2\x17.google.protobuf.StructR\rcaveatContext\x12\x16\n" +
	"\x06result\x18\x03 \x01(\bR\x06result\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\x85\x02\n" +
	"\x11BatchCheckRequest\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.pb.CheckItemR\x05items\x12D\n" +
	"\x11shared_attributes\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x10sharedAttributes\x129\n" +
	"\n" +
	"check_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcheckTime\x12+\n" +
	"\x11consistency_token\x18\x04 \x01(\tR\x10consistencyToken\x12\x1d\n" +
	"\n" +
	"use_strict\x18\x05 \x01(\bR\tuseStrict\"\x91\x02\n" +
	"\tCheckItem\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12!\n" +
	"\fprincipal_id\x18\x02 \x01(\tR\vprincipalId\x12#\n" +
	"\rresource_type\x18\x03 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\x04 \x01(\tR\n" +
	"resourceId\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x127\n" +
	"\n" +
	"attributes\x18\x06 \x01(\v2\x17.google.protobuf.StructR\n" +
	"attributes\x12+\n" +
	"\x11requested_columns\x18\a \x03(\tR\x10requestedColumns\"l\n" +
	"\x12BatchCheckResponse\x12)\n" +
	"\aresults\x18\x01 \x03(\v2\x0f.pb.CheckResultR\aresults\x12+\n" +
	"\x11consistency_token\x18\x02 \x01(\tR\x10consistencyToken\"\xa6\x01\n" +
	"\vCheckResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\aallowed\x18\x02 \x01(\bR\aallowed\x12\x1f\n" +
	"\vdecision_id\x18\x03 \x01(\tR\n" +
	"decisionId\x12\x18\n" +
	"\areasons\x18\x04 \x03(\tR\areasons\x12#\n" +
	"\x05debug\x18\x05 \x01(\v2\r.pb.DebugInfoR\x05debug\"\xd0\x03\n" +
	"\x16LookupResourcesRequest\x12!\n" +
	"\fprincipal_id\x18\x01 \x01(\tR\vprincipalId\x12#\n" +
	"\rresource_type\x18\x02 \x01(\tR\fresourceType\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12,\n" +
	"\x12parent_resource_id\x18\x04 \x01(\tR\x10parentResourceId\x12'\n" +
	"\x0forganization_id\x18\x05 \x01(\tR\x0eorganizationId\x127\n" +
	"\n" +
	"attributes\x18\x06 \x01(\v2\x17.google.protobuf.StructR\n" +
	"attributes\x129\n" +
	"\n" +
	"check_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcheckTime\x12\x12\n" +
	"\x04page\x18\b \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\t \x01(\x05R\bpageSize\x12-\n" +
	"\x12continuation_token\x18\n" +
	" \x01(\tR\x11continuationToken\x12+\n" +
	"\x11consistency_token\x18\v \x01(\tR\x10consistencyToken\"\xc8\x01\n" +
	"\x17LookupResourcesResponse\x120\n" +
	"\tresources\x18\x01 \x03(\v2\x12.pb.ResourceAccessR\tresources\x12-\n" +
	"\x12continuation_token\x18\x02 \x01(\tR\x11continuationToken\x12+\n" +
	"\x11consistency_token\x18\x03 \x01(\tR\x10consistencyToken\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount\"\xb4\x01\n" +
	"\x0eResourceAccess\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12#\n" +
	"\rresource_type\x18\x02 \x01(\tR\fresourceType\x12'\n" +
	"\x0fallowed_actions\x18\x03 \x03(\tR\x0eallowedActions\x123\n" +
	"\bmetadata\x18\x04 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\xfd\x02\n" +
	"\x13CheckColumnsRequest\x12!\n" +
	"\fprincipal_id\x18\x01 \x01(\tR\vprincipalId\x12\x1d\n" +
	"\n" +
	"table_name\x18\x02 \x01(\tR\ttableName\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId\x12+\n" +
	"\x11requested_columns\x18\x04 \x03(\tR\x10requestedColumns\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x127\n" +
	"\n" +
	"attributes\x18\x06 \x01(\v2\x17.google.protobuf.StructR\n" +
	"attributes\x129\n" +
	"\n" +
	"check_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcheckTime\x12+\n" +
	"\x11consistency_token\x18\b \x01(\tR\x10consistencyToken\x12\x1d\n" +
	"\n" +
	"use_strict\x18\t \x01(\bR\tuseStrict\"\xf3\x01\n" +
	"\x14CheckColumnsResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12'\n" +
	"\x0fallowed_columns\x18\x02 \x03(\tR\x0eallowedColumns\x12%\n" +
	"\x0edenied_columns\x18\x03 \x03(\tR\rdeniedColumns\x12#\n" +
	"\rcolumn_groups\x18\x04 \x03(\tR\fcolumnGroups\x12\x1f\n" +
	"\vdecision_id\x18\x05 \x01(\tR\n" +
	"decisionId\x12+\n" +
	"\x11consistency_token\x18\x06 \x01(\tR\x10consistencyToken\"\xb7\x02\n" +
	"\x19ListAllowedColumnsRequest\x12!\n" +
	"\fprincipal_id\x18\x01 \x01(\tR\vprincipalId\x12\x1d\n" +
	"\n" +
	"table_name\x18\x02 \x01(\tR\ttableName\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x127\n" +
	"\n" +
	"attributes\x18\x05 \x01(\v2\x17.google.protobuf.StructR\n" +
	"attributes\x129\n" +
	"\n" +
	"check_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcheckTime\x12+\n" +
	"\x11consistency_token\x18\a \x01(\tR\x10consistencyToken\"\xae\x01\n" +
	"\x1aListAllowedColumnsResponse\x12'\n" +
	"\x0fallowed_columns\x18\x01 \x03(\tR\x0eallowedColumns\x12:\n" +
	"\rcolumn_groups\x18\x02 \x03(\v2\x15.pb.ColumnGroupAccessR\fcolumnGroups\x12+\n" +
	"\x11consistency_token\x18\x03 \x01(\tR\x10consistencyToken\"n\n" +
	"\x11ColumnGroupAccess\x12\x1d\n" +
	"\n" +
	"group_name\x18\x01 \x01(\tR\tgroupName\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\acolumns\x18\x03 \x03(\tR\acolumns\"\xbb\x03\n" +
	"\x0eExplainRequest\x12!\n" +
	"\fprincipal_id\x18\x01 \x01(\tR\vprincipalId\x12#\n" +
	"\rresource_type\x18\x02 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x127\n" +
	"\n" +
	"attributes\x18\x05 \x01(\v2\x17.google.protobuf.StructR\n" +
	"attributes\x12+\n" +
	"\x11requested_columns\x18\x06 \x03(\tR\x10requestedColumns\x129\n" +
	"\n" +
	"check_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcheckTime\x12,\n" +
	"\x12include_tuple_path\x18\b \x01(\bR\x10includeTuplePath\x12'\n" +
	"\x0finclude_caveats\x18\t \x01(\bR\x0eincludeCaveats\x120\n" +
	"\x14include_denied_paths\x18\n" +
	" \x01(\bR\x12includeDeniedPaths\"\x8f\x02\n" +
	"\x0fExplainResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x1f\n" +
	"\vdecision_id\x18\x02 \x01(\tR\n" +
	"decisionId\x122\n" +
	"\rallowed_paths\x18\x03 \x03(\v2\r.pb.TuplePathR\fallowedPaths\x120\n" +
	"\fdenied_paths\x18\x04 \x03(\v2\r.pb.TuplePathR\vdeniedPaths\x12.\n" +
	"\acaveats\x18\x05 \x03(\v2\x14.pb.CaveatEvaluationR\acaveats\x12+\n" +
	"\x11human_explanation\x18\x06 \x01(\tR\x10humanExplanation\"t\n" +
	"\tTuplePath\x12#\n" +
	"\x05nodes\x18\x01 \x03(\v2\r.pb.TupleNodeR\x05nodes\x12\x1d\n" +
	"\n" +
	"is_allowed\x18\x02 \x01(\bR\tisAllowed\x12#\n" +
	"\rdenied_reason\x18\x03 \x01(\tR\fdeniedReason\"\xa7\x01\n" +
	"\tTupleNode\x12\x1f\n" +
	"\vobject_type\x18\x01 \x01(\tR\n" +
	"objectType\x12\x1b\n" +
	"\tobject_id\x18\x02 \x01(\tR\bobjectId\x12\x1a\n" +
	"\brelation\x18\x03 \x01(\tR\brelation\x12!\n" +
	"\fsubject_type\x18\x04 \x01(\tR\vsubjectType\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x05 \x01(\tR\tsubjectId2\x99\x03\n" +
	"\x14AuthorizationService\x12,\n" +
	"\x05Check\x12\x10.pb.CheckRequest\x1a\x11.pb.CheckResponse\x12;\n" +
	"\n" +
	"BatchCheck\x12\x15.pb.BatchCheckRequest\x1a\x16.pb.BatchCheckResponse\x12J\n" +
	"\x0fLookupResources\x12\x1a.pb.LookupResourcesRequest\x1a\x1b.pb.LookupResourcesResponse\x12A\n" +
	"\fCheckColumns\x12\x17.pb.CheckColumnsRequest\x1a\x18.pb.CheckColumnsResponse\x12S\n" +
	"\x12ListAllowedColumns\x12\x1d.pb.ListAllowedColumnsRequest\x1a\x1e.pb.ListAllowedColumnsResponse\x122\n" +
	"\aExplain\x12\x12.pb.ExplainRequest\x1a\x13.pb.ExplainResponseB%Z#github.com/Kisanlink/aaa-service/pbb\x06proto3"

var (
	file_pkg_proto_authz_proto_rawDescOnce sync.Once
	file_pkg_proto_authz_proto_rawDescData []byte
)

func file_pkg_proto_authz_proto_rawDescGZIP() []byte {
	file_pkg_proto_authz_proto_rawDescOnce.Do(func() {
		file_pkg_proto_authz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_authz_proto_rawDesc), len(file_pkg_proto_authz_proto_rawDesc)))
	})
	return file_pkg_proto_authz_proto_rawDescData
}

var file_pkg_proto_authz_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_pkg_proto_authz_proto_goTypes = []any{
	(*CheckRequest)(nil),               // 0: pb.CheckRequest
	(*CheckResponse)(nil),              // 1: pb.CheckResponse
	(*DebugInfo)(nil),                  // 2: pb.DebugInfo
	(*CaveatEvaluation)(nil),           // 3: pb.CaveatEvaluation
	(*BatchCheckRequest)(nil),          // 4: pb.BatchCheckRequest
	(*CheckItem)(nil),                  // 5: pb.CheckItem
	(*BatchCheckResponse)(nil),         // 6: pb.BatchCheckResponse
	(*CheckResult)(nil),                // 7: pb.CheckResult
	(*LookupResourcesRequest)(nil),     // 8: pb.LookupResourcesRequest
	(*LookupResourcesResponse)(nil),    // 9: pb.LookupResourcesResponse
	(*ResourceAccess)(nil),             // 10: pb.ResourceAccess
	(*CheckColumnsRequest)(nil),        // 11: pb.CheckColumnsRequest
	(*CheckColumnsResponse)(nil),       // 12: pb.CheckColumnsResponse
	(*ListAllowedColumnsRequest)(nil),  // 13: pb.ListAllowedColumnsRequest
	(*ListAllowedColumnsResponse)(nil), // 14: pb.ListAllowedColumnsResponse
	(*ColumnGroupAccess)(nil),          // 15: pb.ColumnGroupAccess
	(*ExplainRequest)(nil),             // 16: pb.ExplainRequest
	(*ExplainResponse)(nil),            // 17: pb.ExplainResponse
	(*TuplePath)(nil),                  // 18: pb.TuplePath
	(*TupleNode)(nil),                  // 19: pb.TupleNode
	(*structpb.Struct)(nil),            // 20: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),      // 21: google.protobuf.Timestamp
}
var file_pkg_proto_authz_proto_depIdxs = []int32{
	20, // 0: pb.CheckRequest.attributes:type_name -> google.protobuf.Struct
	21, // 1: pb.CheckRequest.check_time:type_name -> google.protobuf.Timestamp
	2,  // 2: pb.CheckResponse.debug:type_name -> pb.DebugInfo
	3,  // 3: pb.DebugInfo.caveats:type_name -> pb.CaveatEvaluation
	20, // 4: pb.CaveatEvaluation.caveat_context:type_name -> google.protobuf.Struct
	5,  // 5: pb.BatchCheckRequest.items:type_name -> pb.CheckItem
	20, // 6: pb.BatchCheckRequest.shared_attributes:type_name -> google.protobuf.Struct
	21, // 7: pb.BatchCheckRequest.check_time:type_name -> google.protobuf.Timestamp
	20, // 8: pb.CheckItem.attributes:type_name -> google.protobuf.Struct
	7,  // 9: pb.BatchCheckResponse.results:type_name -> pb.CheckResult
	2,  // 10: pb.CheckResult.debug:type_name -> pb.DebugInfo
	20, // 11: pb.LookupResourcesRequest.attributes:type_name -> google.protobuf.Struct
	21, // 12: pb.LookupResourcesRequest.check_time:type_name -> google.protobuf.Timestamp
	10, // 13: pb.LookupResourcesResponse.resources:type_name -> pb.ResourceAccess
	20, // 14: pb.ResourceAccess.metadata:type_name -> google.protobuf.Struct
	20, // 15: pb.CheckColumnsRequest.attributes:type_name -> google.protobuf.Struct
	21, // 16: pb.CheckColumnsRequest.check_time:type_name -> google.protobuf.Timestamp
	20, // 17: pb.ListAllowedColumnsRequest.attributes:type_name -> google.protobuf.Struct
	21, // 18: pb.ListAllowedColumnsRequest.check_time:type_name -> google.protobuf.Timestamp
	15, // 19: pb.ListAllowedColumnsResponse.column_groups:type_name -> pb.ColumnGroupAccess
	20, // 20: pb.ExplainRequest.attributes:type_name -> google.protobuf.Struct
	21, // 21: pb.ExplainRequest.check_time:type_name -> google.protobuf.Timestamp
	18, // 22: pb.ExplainResponse.allowed_paths:type_name -> pb.TuplePath
	18, // 23: pb.ExplainResponse.denied_paths:type_name -> pb.TuplePath
	3,  // 24: pb.ExplainResponse.caveats:type_name -> pb.CaveatEvaluation
	19, // 25: pb.TuplePath.nodes:type_name -> pb.TupleNode
	0,  // 26: pb.AuthorizationService.Check:input_type -> pb.CheckRequest
	4,  // 27: pb.AuthorizationService.BatchCheck:input_type -> pb.BatchCheckRequest
	8,  // 28: pb.AuthorizationService.LookupResources:input_type -> pb.LookupResourcesRequest
	11, // 29: pb.AuthorizationService.CheckColumns:input_type -> pb.CheckColumnsRequest
	13, // 30: pb.AuthorizationService.ListAllowedColumns:input_type -> pb.ListAllowedColumnsRequest
	16, // 31: pb.AuthorizationService.Explain:input_type -> pb.ExplainRequest
	1,  // 32: pb.AuthorizationService.Check:output_type -> pb.CheckResponse
	6,  // 33: pb.AuthorizationService.BatchCheck:output_type -> pb.BatchCheckResponse
	9,  // 34: pb.AuthorizationService.LookupResources:output_type -> pb.LookupResourcesResponse
	12, // 35: pb.AuthorizationService.CheckColumns:output_type -> pb.CheckColumnsResponse
	14, // 36: pb.AuthorizationService.ListAllowedColumns:output_type -> pb.ListAllowedColumnsResponse
	17, // 37: pb.AuthorizationService.Explain:output_type -> pb.ExplainResponse
	32, // [32:38] is the sub-list for method output_type
	26, // [26:32] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_pkg_proto_authz_proto_init() }
func file_pkg_proto_authz_proto_init() {
	if File_pkg_proto_authz_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_authz_proto_rawDesc), len(file_pkg_proto_authz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_authz_proto_goTypes,
		DependencyIndexes: file_pkg_proto_authz_proto_depIdxs,
		MessageInfos:      file_pkg_proto_authz_proto_msgTypes,
	}.Build()
	File_pkg_proto_authz_proto = out.File
	file_pkg_proto_authz_proto_goTypes = nil
	file_pkg_proto_authz_proto_depIdxs = nil
}
