// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: catalog.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Action model
type Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	IsStatic      bool                   `protobuf:"varint,4,opt,name=is_static,json=isStatic,proto3" json:"is_static,omitempty"`   // Static (built-in) vs dynamic (service-defined)
	ServiceId     string                 `protobuf:"bytes,5,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"` // For dynamic actions
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Action) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Action) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Action) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Action) GetIsStatic() bool {
	if x != nil {
		return x.IsStatic
	}
	return false
}

func (x *Action) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *Action) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Action) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Action) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Resource model
type Resource struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type           string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // e.g., "aaa/table", "aaa/database", "aaa/api_endpoint"
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ParentId       string                 `protobuf:"bytes,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	OwnerId        string                 `protobuf:"bytes,6,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,7,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	IsActive       bool                   `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Parent         *Resource              `protobuf:"bytes,12,opt,name=parent,proto3" json:"parent,omitempty"`
	Children       []*Resource            `protobuf:"bytes,13,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *Resource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Resource) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Resource) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Resource) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Resource) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Resource) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Resource) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Resource) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Resource) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Resource) GetParent() *Resource {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *Resource) GetChildren() []*Resource {
	if x != nil {
		return x.Children
	}
	return nil
}

// Enhanced Role model with scope (Catalog version)
type CatalogRole struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Scope          string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`                                         // "GLOBAL" or "ORG"
	OrganizationId string                 `protobuf:"bytes,5,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"` // Required when scope is "ORG"
	Version        int32                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	ParentId       string                 `protobuf:"bytes,7,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	IsActive       bool                   `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Parent         *CatalogRole           `protobuf:"bytes,12,opt,name=parent,proto3" json:"parent,omitempty"`
	Children       []*CatalogRole         `protobuf:"bytes,13,rep,name=children,proto3" json:"children,omitempty"`
	Permissions    []*CatalogPermission   `protobuf:"bytes,14,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CatalogRole) Reset() {
	*x = CatalogRole{}
	mi := &file_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogRole) ProtoMessage() {}

func (x *CatalogRole) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogRole.ProtoReflect.Descriptor instead.
func (*CatalogRole) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *CatalogRole) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CatalogRole) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CatalogRole) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CatalogRole) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *CatalogRole) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CatalogRole) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CatalogRole) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *CatalogRole) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CatalogRole) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CatalogRole) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CatalogRole) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *CatalogRole) GetParent() *CatalogRole {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *CatalogRole) GetChildren() []*CatalogRole {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *CatalogRole) GetPermissions() []*CatalogPermission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// Permission model (Catalog version)
type CatalogPermission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ResourceId    string                 `protobuf:"bytes,4,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ActionId      string                 `protobuf:"bytes,5,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	IsActive      bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Resource      *Resource              `protobuf:"bytes,9,opt,name=resource,proto3" json:"resource,omitempty"`
	Action        *Action                `protobuf:"bytes,10,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatalogPermission) Reset() {
	*x = CatalogPermission{}
	mi := &file_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogPermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogPermission) ProtoMessage() {}

func (x *CatalogPermission) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogPermission.ProtoReflect.Descriptor instead.
func (*CatalogPermission) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *CatalogPermission) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CatalogPermission) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CatalogPermission) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CatalogPermission) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *CatalogPermission) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *CatalogPermission) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CatalogPermission) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CatalogPermission) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *CatalogPermission) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *CatalogPermission) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

// Register Action Request
type RegisterActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	IsStatic      bool                   `protobuf:"varint,3,opt,name=is_static,json=isStatic,proto3" json:"is_static,omitempty"`
	ServiceId     string                 `protobuf:"bytes,4,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterActionRequest) Reset() {
	*x = RegisterActionRequest{}
	mi := &file_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterActionRequest) ProtoMessage() {}

func (x *RegisterActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterActionRequest.ProtoReflect.Descriptor instead.
func (*RegisterActionRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterActionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterActionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RegisterActionRequest) GetIsStatic() bool {
	if x != nil {
		return x.IsStatic
	}
	return false
}

func (x *RegisterActionRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *RegisterActionRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Register Action Response
type RegisterActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Action        *Action                `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterActionResponse) Reset() {
	*x = RegisterActionResponse{}
	mi := &file_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterActionResponse) ProtoMessage() {}

func (x *RegisterActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterActionResponse.ProtoReflect.Descriptor instead.
func (*RegisterActionResponse) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterActionResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *RegisterActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterActionResponse) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

// List Actions Request
type ListActionsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IncludeStatic  bool                   `protobuf:"varint,1,opt,name=include_static,json=includeStatic,proto3" json:"include_static,omitempty"`
	IncludeDynamic bool                   `protobuf:"varint,2,opt,name=include_dynamic,json=includeDynamic,proto3" json:"include_dynamic,omitempty"`
	ServiceId      string                 `protobuf:"bytes,3,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Page           int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize       int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListActionsRequest) Reset() {
	*x = ListActionsRequest{}
	mi := &file_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActionsRequest) ProtoMessage() {}

func (x *ListActionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActionsRequest.ProtoReflect.Descriptor instead.
func (*ListActionsRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *ListActionsRequest) GetIncludeStatic() bool {
	if x != nil {
		return x.IncludeStatic
	}
	return false
}

func (x *ListActionsRequest) GetIncludeDynamic() bool {
	if x != nil {
		return x.IncludeDynamic
	}
	return false
}

func (x *ListActionsRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ListActionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListActionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// List Actions Response
type ListActionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Actions       []*Action              `protobuf:"bytes,3,rep,name=actions,proto3" json:"actions,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActionsResponse) Reset() {
	*x = ListActionsResponse{}
	mi := &file_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActionsResponse) ProtoMessage() {}

func (x *ListActionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActionsResponse.ProtoReflect.Descriptor instead.
func (*ListActionsResponse) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *ListActionsResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ListActionsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListActionsResponse) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *ListActionsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListActionsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListActionsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Register Resource Request
type RegisterResourceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ParentId       string                 `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	OwnerId        string                 `protobuf:"bytes,5,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,6,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterResourceRequest) Reset() {
	*x = RegisterResourceRequest{}
	mi := &file_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResourceRequest) ProtoMessage() {}

func (x *RegisterResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResourceRequest.ProtoReflect.Descriptor instead.
func (*RegisterResourceRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterResourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterResourceRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RegisterResourceRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RegisterResourceRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *RegisterResourceRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *RegisterResourceRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *RegisterResourceRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Register Resource Response
type RegisterResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Resource      *Resource              `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResourceResponse) Reset() {
	*x = RegisterResourceResponse{}
	mi := &file_catalog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResourceResponse) ProtoMessage() {}

func (x *RegisterResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResourceResponse.ProtoReflect.Descriptor instead.
func (*RegisterResourceResponse) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterResourceResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *RegisterResourceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResourceResponse) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

// Set Resource Parent Request
type SetResourceParentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ParentId      string                 `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResourceParentRequest) Reset() {
	*x = SetResourceParentRequest{}
	mi := &file_catalog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResourceParentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResourceParentRequest) ProtoMessage() {}

func (x *SetResourceParentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResourceParentRequest.ProtoReflect.Descriptor instead.
func (*SetResourceParentRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{10}
}

func (x *SetResourceParentRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *SetResourceParentRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

// Set Resource Parent Response
type SetResourceParentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Resource      *Resource              `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResourceParentResponse) Reset() {
	*x = SetResourceParentResponse{}
	mi := &file_catalog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResourceParentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResourceParentResponse) ProtoMessage() {}

func (x *SetResourceParentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResourceParentResponse.ProtoReflect.Descriptor instead.
func (*SetResourceParentResponse) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{11}
}

func (x *SetResourceParentResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *SetResourceParentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SetResourceParentResponse) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

// List Resources Request
type ListResourcesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Type            string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	ParentId        string                 `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	OwnerId         string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	OrganizationId  string                 `protobuf:"bytes,4,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	IncludeChildren bool                   `protobuf:"varint,5,opt,name=include_children,json=includeChildren,proto3" json:"include_children,omitempty"`
	Page            int32                  `protobuf:"varint,6,opt,name=page,proto3" json:"page,omitempty"`
	PageSize        int32                  `protobuf:"varint,7,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListResourcesRequest) Reset() {
	*x = ListResourcesRequest{}
	mi := &file_catalog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesRequest) ProtoMessage() {}

func (x *ListResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesRequest.ProtoReflect.Descriptor instead.
func (*ListResourcesRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{12}
}

func (x *ListResourcesRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListResourcesRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *ListResourcesRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *ListResourcesRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListResourcesRequest) GetIncludeChildren() bool {
	if x != nil {
		return x.IncludeChildren
	}
	return false
}

func (x *ListResourcesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListResourcesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// List Resources Response
type ListResourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Resources     []*Resource            `protobuf:"bytes,3,rep,name=resources,proto3" json:"resources,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesResponse) Reset() {
	*x = ListResourcesResponse{}
	mi := &file_catalog_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesResponse) ProtoMessage() {}

func (x *ListResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesResponse.ProtoReflect.Descriptor instead.
func (*ListResourcesResponse) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{13}
}

func (x *ListResourcesResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ListResourcesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListResourcesResponse) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ListResourcesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListResourcesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListResourcesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Create Role Request
type CreateRoleRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Scope          string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"` // "GLOBAL" or "ORG"
	OrganizationId string                 `protobuf:"bytes,4,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ParentId       string                 `protobuf:"bytes,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	PermissionIds  []string               `protobuf:"bytes,6,rep,name=permission_ids,json=permissionIds,proto3" json:"permission_ids,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_catalog_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{14}
}

func (x *CreateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateRoleRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *CreateRoleRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateRoleRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *CreateRoleRequest) GetPermissionIds() []string {
	if x != nil {
		return x.PermissionIds
	}
	return nil
}

func (x *CreateRoleRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Create Role Response
type CreateRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Role          *CatalogRole           `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleResponse) Reset() {
	*x = CreateRoleResponse{}
	mi := &file_catalog_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleResponse) ProtoMessage() {}

func (x *CreateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleResponse.ProtoReflect.Descriptor instead.
func (*CreateRoleResponse) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{15}
}

func (x *CreateRoleResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *CreateRoleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateRoleResponse) GetRole() *CatalogRole {
	if x != nil {
		return x.Role
	}
	return nil
}

// List Roles Request
type ListRolesRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Scope              string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"` // Filter by scope
	OrganizationId     string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	IncludeInactive    bool                   `protobuf:"varint,3,opt,name=include_inactive,json=includeInactive,proto3" json:"include_inactive,omitempty"`
	IncludePermissions bool                   `protobuf:"varint,4,opt,name=include_permissions,json=includePermissions,proto3" json:"include_permissions,omitempty"`
	Page               int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize           int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListRolesRequest) Reset() {
	*x = ListRolesRequest{}
	mi := &file_catalog_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesRequest) ProtoMessage() {}

func (x *ListRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesRequest.ProtoReflect.Descriptor instead.
func (*ListRolesRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{16}
}

func (x *ListRolesRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *ListRolesRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListRolesRequest) GetIncludeInactive() bool {
	if x != nil {
		return x.IncludeInactive
	}
	return false
}

func (x *ListRolesRequest) GetIncludePermissions() bool {
	if x != nil {
		return x.IncludePermissions
	}
	return false
}

func (x *ListRolesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRolesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// List Roles Response
type ListRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Roles         []*CatalogRole         `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesResponse) Reset() {
	*x = ListRolesResponse{}
	mi := &file_catalog_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesResponse) ProtoMessage() {}

func (x *ListRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesResponse.ProtoReflect.Descriptor instead.
func (*ListRolesResponse) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{17}
}

func (x *ListRolesResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ListRolesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListRolesResponse) GetRoles() []*CatalogRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ListRolesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListRolesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRolesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Create Permission Request
type CreatePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ResourceId    string                 `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ActionId      string                 `protobuf:"bytes,4,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermissionRequest) Reset() {
	*x = CreatePermissionRequest{}
	mi := &file_catalog_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionRequest) ProtoMessage() {}

func (x *CreatePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionRequest.ProtoReflect.Descriptor instead.
func (*CreatePermissionRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{18}
}

func (x *CreatePermissionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePermissionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePermissionRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *CreatePermissionRequest) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

// Create Permission Response
type CreatePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Permission    *CatalogPermission     `protobuf:"bytes,3,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermissionResponse) Reset() {
	*x = CreatePermissionResponse{}
	mi := &file_catalog_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionResponse) ProtoMessage() {}

func (x *CreatePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionResponse.ProtoReflect.Descriptor instead.
func (*CreatePermissionResponse) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{19}
}

func (x *CreatePermissionResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *CreatePermissionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreatePermissionResponse) GetPermission() *CatalogPermission {
	if x != nil {
		return x.Permission
	}
	return nil
}

// Attach Permissions Request
type AttachPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        string                 `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	PermissionIds []string               `protobuf:"bytes,2,rep,name=permission_ids,json=permissionIds,proto3" json:"permission_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachPermissionsRequest) Reset() {
	*x = AttachPermissionsRequest{}
	mi := &file_catalog_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachPermissionsRequest) ProtoMessage() {}

func (x *AttachPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachPermissionsRequest.ProtoReflect.Descriptor instead.
func (*AttachPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{20}
}

func (x *AttachPermissionsRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *AttachPermissionsRequest) GetPermissionIds() []string {
	if x != nil {
		return x.PermissionIds
	}
	return nil
}

// Attach Permissions Response
type AttachPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Role          *CatalogRole           `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachPermissionsResponse) Reset() {
	*x = AttachPermissionsResponse{}
	mi := &file_catalog_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachPermissionsResponse) ProtoMessage() {}

func (x *AttachPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachPermissionsResponse.ProtoReflect.Descriptor instead.
func (*AttachPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{21}
}

func (x *AttachPermissionsResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *AttachPermissionsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AttachPermissionsResponse) GetRole() *CatalogRole {
	if x != nil {
		return x.Role
	}
	return nil
}

// List Permissions Request
type ListPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        string                 `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	ResourceId    string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ActionId      string                 `protobuf:"bytes,3,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionsRequest) Reset() {
	*x = ListPermissionsRequest{}
	mi := &file_catalog_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsRequest) ProtoMessage() {}

func (x *ListPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsRequest.ProtoReflect.Descriptor instead.
func (*ListPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{22}
}

func (x *ListPermissionsRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *ListPermissionsRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *ListPermissionsRequest) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *ListPermissionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPermissionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// List Permissions Response
type ListPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Permissions   []*CatalogPermission   `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionsResponse) Reset() {
	*x = ListPermissionsResponse{}
	mi := &file_catalog_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsResponse) ProtoMessage() {}

func (x *ListPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsResponse.ProtoReflect.Descriptor instead.
func (*ListPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{23}
}

func (x *ListPermissionsResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ListPermissionsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListPermissionsResponse) GetPermissions() []*CatalogPermission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *ListPermissionsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListPermissionsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPermissionsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Seed Roles and Permissions Request
type SeedRolesAndPermissionsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Force          bool                   `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`                                        // Force re-seed even if data exists
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"` // Optional - seed for specific org
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SeedRolesAndPermissionsRequest) Reset() {
	*x = SeedRolesAndPermissionsRequest{}
	mi := &file_catalog_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeedRolesAndPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeedRolesAndPermissionsRequest) ProtoMessage() {}

func (x *SeedRolesAndPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeedRolesAndPermissionsRequest.ProtoReflect.Descriptor instead.
func (*SeedRolesAndPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{24}
}

func (x *SeedRolesAndPermissionsRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *SeedRolesAndPermissionsRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

// Seed Roles and Permissions Response
type SeedRolesAndPermissionsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	StatusCode         int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message            string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RolesCreated       int32                  `protobuf:"varint,3,opt,name=roles_created,json=rolesCreated,proto3" json:"roles_created,omitempty"`
	PermissionsCreated int32                  `protobuf:"varint,4,opt,name=permissions_created,json=permissionsCreated,proto3" json:"permissions_created,omitempty"`
	ResourcesCreated   int32                  `protobuf:"varint,5,opt,name=resources_created,json=resourcesCreated,proto3" json:"resources_created,omitempty"`
	ActionsCreated     int32                  `protobuf:"varint,6,opt,name=actions_created,json=actionsCreated,proto3" json:"actions_created,omitempty"`
	CreatedRoles       []string               `protobuf:"bytes,7,rep,name=created_roles,json=createdRoles,proto3" json:"created_roles,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SeedRolesAndPermissionsResponse) Reset() {
	*x = SeedRolesAndPermissionsResponse{}
	mi := &file_catalog_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeedRolesAndPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeedRolesAndPermissionsResponse) ProtoMessage() {}

func (x *SeedRolesAndPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeedRolesAndPermissionsResponse.ProtoReflect.Descriptor instead.
func (*SeedRolesAndPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{25}
}

func (x *SeedRolesAndPermissionsResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *SeedRolesAndPermissionsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SeedRolesAndPermissionsResponse) GetRolesCreated() int32 {
	if x != nil {
		return x.RolesCreated
	}
	return 0
}

func (x *SeedRolesAndPermissionsResponse) GetPermissionsCreated() int32 {
	if x != nil {
		return x.PermissionsCreated
	}
	return 0
}

func (x *SeedRolesAndPermissionsResponse) GetResourcesCreated() int32 {
	if x != nil {
		return x.ResourcesCreated
	}
	return 0
}

func (x *SeedRolesAndPermissionsResponse) GetActionsCreated() int32 {
	if x != nil {
		return x.ActionsCreated
	}
	return 0
}

func (x *SeedRolesAndPermissionsResponse) GetCreatedRoles() []string {
	if x != nil {
		return x.CreatedRoles
	}
	return nil
}

var File_catalog_proto protoreflect.FileDescriptor

const file_catalog_proto_rawDesc = "" +
	"\n" +
	"\rcatalog.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf3\x02\n" +
	"\x06Action\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_static\x18\x04 \x01(\bR\bisStatic\x12\x1d\n" +
	"\n" +
	"service_id\x18\x05 \x01(\tR\tserviceId\x124\n" +
	"\bmetadata\x18\x06 \x03(\v2\x18.pb.Action.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9d\x04\n" +
	"\bResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tparent_id\x18\x05 \x01(\tR\bparentId\x12\x19\n" +
	"\bowner_id\x18\x06 \x01(\tR\aownerId\x12'\n" +
	"\x0forganization_id\x18\a \x01(\tR\x0eorganizationId\x12\x1b\n" +
	"\tis_active\x18\b \x01(\bR\bisActive\x126\n" +
	"\bmetadata\x18\t \x03(\v2\x1a.pb.Resource.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12$\n" +
	"\x06parent\x18\f \x01(\v2\f.pb.ResourceR\x06parent\x12(\n" +
	"\bchildren\x18\r \x03(\v2\f.pb.ResourceR\bchildren\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe3\x04\n" +
	"\vCatalogRole\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\x12'\n" +
	"\x0forganization_id\x18\x05 \x01(\tR\x0eorganizationId\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x05R\aversion\x12\x1b\n" +
	"\tparent_id\x18\a \x01(\tR\bparentId\x12\x1b\n" +
	"\tis_active\x18\b \x01(\bR\bisActive\x129\n" +
	"\bmetadata\x18\t \x03(\v2\x1d.pb.CatalogRole.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12'\n" +
	"\x06parent\x18\f \x01(\v2\x0f.pb.CatalogRoleR\x06parent\x12+\n" +
	"\bchildren\x18\r \x03(\v2\x0f.pb.CatalogRoleR\bchildren\x127\n" +
	"\vpermissions\x18\x0e \x03(\v2\x15.pb.CatalogPermissionR\vpermissions\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf8\x02\n" +
	"\x11CatalogPermission\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vresource_id\x18\x04 \x01(\tR\n" +
	"resourceId\x12\x1b\n" +
	"\taction_id\x18\x05 \x01(\tR\bactionId\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12(\n" +
	"\bresource\x18\t \x01(\v2\f.pb.ResourceR\bresource\x12\"\n" +
	"\x06action\x18\n" +
	" \x01(\v2\n" +
	".pb.ActionR\x06action\"\x8b\x02\n" +
	"\x15RegisterActionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_static\x18\x03 \x01(\bR\bisStatic\x12\x1d\n" +
	"\n" +
	"service_id\x18\x04 \x01(\tR\tserviceId\x12C\n" +
	"\bmetadata\x18\x05 \x03(\v2'.pb.RegisterActionRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"w\n" +
	"\x16RegisterActionResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\"\n" +
	"\x06action\x18\x03 \x01(\v2\n" +
	".pb.ActionR\x06action\"\xb4\x01\n" +
	"\x12ListActionsRequest\x12%\n" +
	"\x0einclude_static\x18\x01 \x01(\bR\rincludeStatic\x12'\n" +
	"\x0finclude_dynamic\x18\x02 \x01(\bR\x0eincludeDynamic\x12\x1d\n" +
	"\n" +
	"service_id\x18\x03 \x01(\tR\tserviceId\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"\xc8\x01\n" +
	"\x13ListActionsResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12$\n" +
	"\aactions\x18\x03 \x03(\v2\n" +
	".pb.ActionR\aactions\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\"\xc8\x02\n" +
	"\x17RegisterResourceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\tR\bparentId\x12\x19\n" +
	"\bowner_id\x18\x05 \x01(\tR\aownerId\x12'\n" +
	"\x0forganization_id\x18\x06 \x01(\tR\x0eorganizationId\x12E\n" +
	"\bmetadata\x18\a \x03(\v2).pb.RegisterResourceRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x7f\n" +
	"\x18RegisterResourceResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\bresource\x18\x03 \x01(\v2\f.pb.ResourceR\bresource\"X\n" +
	"\x18SetResourceParentRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\tR\bparentId\"\x80\x01\n" +
	"\x19SetResourceParentResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\bresource\x18\x03 \x01(\v2\f.pb.ResourceR\bresource\"\xe7\x01\n" +
	"\x14ListResourcesRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\tR\bparentId\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x12'\n" +
	"\x0forganization_id\x18\x04 \x01(\tR\x0eorganizationId\x12)\n" +
	"\x10include_children\x18\x05 \x01(\bR\x0fincludeChildren\x12\x12\n" +
	"\x04page\x18\x06 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\a \x01(\x05R\bpageSize\"\xd0\x01\n" +
	"\x15ListResourcesResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\tresources\x18\x03 \x03(\v2\f.pb.ResourceR\tresources\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\"\xca\x02\n" +
	"\x11CreateRoleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x12'\n" +
	"\x0forganization_id\x18\x04 \x01(\tR\x0eorganizationId\x12\x1b\n" +
	"\tparent_id\x18\x05 \x01(\tR\bparentId\x12%\n" +
	"\x0epermission_ids\x18\x06 \x03(\tR\rpermissionIds\x12?\n" +
	"\bmetadata\x18\a \x03(\v2#.pb.CreateRoleRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"t\n" +
	"\x12CreateRoleResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\x04role\x18\x03 \x01(\v2\x0f.pb.CatalogRoleR\x04role\"\xde\x01\n" +
	"\x10ListRolesRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12)\n" +
	"\x10include_inactive\x18\x03 \x01(\bR\x0fincludeInactive\x12/\n" +
	"\x13include_permissions\x18\x04 \x01(\bR\x12includePermissions\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\"\xc7\x01\n" +
	"\x11ListRolesResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x05roles\x18\x03 \x03(\v2\x0f.pb.CatalogRoleR\x05roles\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\"\x8d\x01\n" +
	"\x17CreatePermissionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId\x12\x1b\n" +
	"\taction_id\x18\x04 \x01(\tR\bactionId\"\x8c\x01\n" +
	"\x18CreatePermissionResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x125\n" +
	"\n" +
	"permission\x18\x03 \x01(\v2\x15.pb.CatalogPermissionR\n" +
	"permission\"Z\n" +
	"\x18AttachPermissionsRequest\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\x12%\n" +
	"\x0epermission_ids\x18\x02 \x03(\tR\rpermissionIds\"{\n" +
	"\x19AttachPermissionsResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\x04role\x18\x03 \x01(\v2\x0f.pb.CatalogRoleR\x04role\"\xa0\x01\n" +
	"\x16ListPermissionsRequest\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\x12\x1b\n" +
	"\taction_id\x18\x03 \x01(\tR\bactionId\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"\xdf\x01\n" +
	"\x17ListPermissionsResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x127\n" +
	"\vpermissions\x18\x03 \x03(\v2\x15.pb.CatalogPermissionR\vpermissions\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\"_\n" +
	"\x1eSeedRolesAndPermissionsRequest\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\"\xad\x02\n" +
	"\x1fSeedRolesAndPermissionsResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rroles_created\x18\x03 \x01(\x05R\frolesCreated\x12/\n" +
	"\x13permissions_created\x18\x04 \x01(\x05R\x12permissionsCreated\x12+\n" +
	"\x11resources_created\x18\x05 \x01(\x05R\x10resourcesCreated\x12'\n" +
	"\x0factions_created\x18\x06 \x01(\x05R\x0eactionsCreated\x12#\n" +
	"\rcreated_roles\x18\a \x03(\tR\fcreatedRoles2\xc8\x06\n" +
	"\x0eCatalogService\x12G\n" +
	"\x0eRegisterAction\x12\x19.pb.RegisterActionRequest\x1a\x1a.pb.RegisterActionResponse\x12>\n" +
	"\vListActions\x12\x16.pb.ListActionsRequest\x1a\x17.pb.ListActionsResponse\x12M\n" +
	"\x10RegisterResource\x12\x1b.pb.RegisterResourceRequest\x1a\x1c.pb.RegisterResourceResponse\x12P\n" +
	"\x11SetResourceParent\x12\x1c.pb.SetResourceParentRequest\x1a\x1d.pb.SetResourceParentResponse\x12D\n" +
	"\rListResources\x12\x18.pb.ListResourcesRequest\x1a\x19.pb.ListResourcesResponse\x12;\n" +
	"\n" +
	"CreateRole\x12\x15.pb.CreateRoleRequest\x1a\x16.pb.CreateRoleResponse\x128\n" +
	"\tListRoles\x12\x14.pb.ListRolesRequest\x1a\x15.pb.ListRolesResponse\x12M\n" +
	"\x10CreatePermission\x12\x1b.pb.CreatePermissionRequest\x1a\x1c.pb.CreatePermissionResponse\x12P\n" +
	"\x11AttachPermissions\x12\x1c.pb.AttachPermissionsRequest\x1a\x1d.pb.AttachPermissionsResponse\x12J\n" +
	"\x0fListPermissions\x12\x1a.pb.ListPermissionsRequest\x1a\x1b.pb.ListPermissionsResponse\x12b\n" +
	"\x17SeedRolesAndPermissions\x12\".pb.SeedRolesAndPermissionsRequest\x1a#.pb.SeedRolesAndPermissionsResponseB/Z-github.com/Kisanlink/farmers-module/pkg/protob\x06proto3"

var (
	file_catalog_proto_rawDescOnce sync.Once
	file_catalog_proto_rawDescData []byte
)

func file_catalog_proto_rawDescGZIP() []byte {
	file_catalog_proto_rawDescOnce.Do(func() {
		file_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_proto_rawDesc), len(file_catalog_proto_rawDesc)))
	})
	return file_catalog_proto_rawDescData
}

var file_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_catalog_proto_goTypes = []any{
	(*Action)(nil),                          // 0: pb.Action
	(*Resource)(nil),                        // 1: pb.Resource
	(*CatalogRole)(nil),                     // 2: pb.CatalogRole
	(*CatalogPermission)(nil),               // 3: pb.CatalogPermission
	(*RegisterActionRequest)(nil),           // 4: pb.RegisterActionRequest
	(*RegisterActionResponse)(nil),          // 5: pb.RegisterActionResponse
	(*ListActionsRequest)(nil),              // 6: pb.ListActionsRequest
	(*ListActionsResponse)(nil),             // 7: pb.ListActionsResponse
	(*RegisterResourceRequest)(nil),         // 8: pb.RegisterResourceRequest
	(*RegisterResourceResponse)(nil),        // 9: pb.RegisterResourceResponse
	(*SetResourceParentRequest)(nil),        // 10: pb.SetResourceParentRequest
	(*SetResourceParentResponse)(nil),       // 11: pb.SetResourceParentResponse
	(*ListResourcesRequest)(nil),            // 12: pb.ListResourcesRequest
	(*ListResourcesResponse)(nil),           // 13: pb.ListResourcesResponse
	(*CreateRoleRequest)(nil),               // 14: pb.CreateRoleRequest
	(*CreateRoleResponse)(nil),              // 15: pb.CreateRoleResponse
	(*ListRolesRequest)(nil),                // 16: pb.ListRolesRequest
	(*ListRolesResponse)(nil),               // 17: pb.ListRolesResponse
	(*CreatePermissionRequest)(nil),         // 18: pb.CreatePermissionRequest
	(*CreatePermissionResponse)(nil),        // 19: pb.CreatePermissionResponse
	(*AttachPermissionsRequest)(nil),        // 20: pb.AttachPermissionsRequest
	(*AttachPermissionsResponse)(nil),       // 21: pb.AttachPermissionsResponse
	(*ListPermissionsRequest)(nil),          // 22: pb.ListPermissionsRequest
	(*ListPermissionsResponse)(nil),         // 23: pb.ListPermissionsResponse
	(*SeedRolesAndPermissionsRequest)(nil),  // 24: pb.SeedRolesAndPermissionsRequest
	(*SeedRolesAndPermissionsResponse)(nil), // 25: pb.SeedRolesAndPermissionsResponse
	nil,                                     // 26: pb.Action.MetadataEntry
	nil,                                     // 27: pb.Resource.MetadataEntry
	nil,                                     // 28: pb.CatalogRole.MetadataEntry
	nil,                                     // 29: pb.RegisterActionRequest.MetadataEntry
	nil,                                     // 30: pb.RegisterResourceRequest.MetadataEntry
	nil,                                     // 31: pb.CreateRoleRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil),           // 32: google.protobuf.Timestamp
}
var file_catalog_proto_depIdxs = []int32{
	26, // 0: pb.Action.metadata:type_name -> pb.Action.MetadataEntry
	32, // 1: pb.Action.created_at:type_name -> google.protobuf.Timestamp
	32, // 2: pb.Action.updated_at:type_name -> google.protobuf.Timestamp
	27, // 3: pb.Resource.metadata:type_name -> pb.Resource.MetadataEntry
	32, // 4: pb.Resource.created_at:type_name -> google.protobuf.Timestamp
	32, // 5: pb.Resource.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 6: pb.Resource.parent:type_name -> pb.Resource
	1,  // 7: pb.Resource.children:type_name -> pb.Resource
	28, // 8: pb.CatalogRole.metadata:type_name -> pb.CatalogRole.MetadataEntry
	32, // 9: pb.CatalogRole.created_at:type_name -> google.protobuf.Timestamp
	32, // 10: pb.CatalogRole.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 11: pb.CatalogRole.parent:type_name -> pb.CatalogRole
	2,  // 12: pb.CatalogRole.children:type_name -> pb.CatalogRole
	3,  // 13: pb.CatalogRole.permissions:type_name -> pb.CatalogPermission
	32, // 14: pb.CatalogPermission.created_at:type_name -> google.protobuf.Timestamp
	32, // 15: pb.CatalogPermission.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 16: pb.CatalogPermission.resource:type_name -> pb.Resource
	0,  // 17: pb.CatalogPermission.action:type_name -> pb.Action
	29, // 18: pb.RegisterActionRequest.metadata:type_name -> pb.RegisterActionRequest.MetadataEntry
	0,  // 19: pb.RegisterActionResponse.action:type_name -> pb.Action
	0,  // 20: pb.ListActionsResponse.actions:type_name -> pb.Action
	30, // 21: pb.RegisterResourceRequest.metadata:type_name -> pb.RegisterResourceRequest.MetadataEntry
	1,  // 22: pb.RegisterResourceResponse.resource:type_name -> pb.Resource
	1,  // 23: pb.SetResourceParentResponse.resource:type_name -> pb.Resource
	1,  // 24: pb.ListResourcesResponse.resources:type_name -> pb.Resource
	31, // 25: pb.CreateRoleRequest.metadata:type_name -> pb.CreateRoleRequest.MetadataEntry
	2,  // 26: pb.CreateRoleResponse.role:type_name -> pb.CatalogRole
	2,  // 27: pb.ListRolesResponse.roles:type_name -> pb.CatalogRole
	3,  // 28: pb.CreatePermissionResponse.permission:type_name -> pb.CatalogPermission
	2,  // 29: pb.AttachPermissionsResponse.role:type_name -> pb.CatalogRole
	3,  // 30: pb.ListPermissionsResponse.permissions:type_name -> pb.CatalogPermission
	4,  // 31: pb.CatalogService.RegisterAction:input_type -> pb.RegisterActionRequest
	6,  // 32: pb.CatalogService.ListActions:input_type -> pb.ListActionsRequest
	8,  // 33: pb.CatalogService.RegisterResource:input_type -> pb.RegisterResourceRequest
	10, // 34: pb.CatalogService.SetResourceParent:input_type -> pb.SetResourceParentRequest
	12, // 35: pb.CatalogService.ListResources:input_type -> pb.ListResourcesRequest
	14, // 36: pb.CatalogService.CreateRole:input_type -> pb.CreateRoleRequest
	16, // 37: pb.CatalogService.ListRoles:input_type -> pb.ListRolesRequest
	18, // 38: pb.CatalogService.CreatePermission:input_type -> pb.CreatePermissionRequest
	20, // 39: pb.CatalogService.AttachPermissions:input_type -> pb.AttachPermissionsRequest
	22, // 40: pb.CatalogService.ListPermissions:input_type -> pb.ListPermissionsRequest
	24, // 41: pb.CatalogService.SeedRolesAndPermissions:input_type -> pb.SeedRolesAndPermissionsRequest
	5,  // 42: pb.CatalogService.RegisterAction:output_type -> pb.RegisterActionResponse
	7,  // 43: pb.CatalogService.ListActions:output_type -> pb.ListActionsResponse
	9,  // 44: pb.CatalogService.RegisterResource:output_type -> pb.RegisterResourceResponse
	11, // 45: pb.CatalogService.SetResourceParent:output_type -> pb.SetResourceParentResponse
	13, // 46: pb.CatalogService.ListResources:output_type -> pb.ListResourcesResponse
	15, // 47: pb.CatalogService.CreateRole:output_type -> pb.CreateRoleResponse
	17, // 48: pb.CatalogService.ListRoles:output_type -> pb.ListRolesResponse
	19, // 49: pb.CatalogService.CreatePermission:output_type -> pb.CreatePermissionResponse
	21, // 50: pb.CatalogService.AttachPermissions:output_type -> pb.AttachPermissionsResponse
	23, // 51: pb.CatalogService.ListPermissions:output_type -> pb.ListPermissionsResponse
	25, // 52: pb.CatalogService.SeedRolesAndPermissions:output_type -> pb.SeedRolesAndPermissionsResponse
	42, // [42:53] is the sub-list for method output_type
	31, // [31:42] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_catalog_proto_init() }
func file_catalog_proto_init() {
	if File_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_proto_rawDesc), len(file_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catalog_proto_goTypes,
		DependencyIndexes: file_catalog_proto_depIdxs,
		MessageInfos:      file_catalog_proto_msgTypes,
	}.Build()
	File_catalog_proto = out.File
	file_catalog_proto_goTypes = nil
	file_catalog_proto_depIdxs = nil
}
