// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: token.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JWT Token Validation Request
type ValidateTokenRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Token               string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	IncludeUserDetails  bool                   `protobuf:"varint,2,opt,name=include_user_details,json=includeUserDetails,proto3" json:"include_user_details,omitempty"`
	IncludePermissions  bool                   `protobuf:"varint,3,opt,name=include_permissions,json=includePermissions,proto3" json:"include_permissions,omitempty"`
	IncludeOrganization bool                   `protobuf:"varint,4,opt,name=include_organization,json=includeOrganization,proto3" json:"include_organization,omitempty"`
	RequiredPermissions []string               `protobuf:"bytes,5,rep,name=required_permissions,json=requiredPermissions,proto3" json:"required_permissions,omitempty"`
	ResourceContext     string                 `protobuf:"bytes,6,opt,name=resource_context,json=resourceContext,proto3" json:"resource_context,omitempty"`
	StrictValidation    bool                   `protobuf:"varint,7,opt,name=strict_validation,json=strictValidation,proto3" json:"strict_validation,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_token_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_token_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_token_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ValidateTokenRequest) GetIncludeUserDetails() bool {
	if x != nil {
		return x.IncludeUserDetails
	}
	return false
}

func (x *ValidateTokenRequest) GetIncludePermissions() bool {
	if x != nil {
		return x.IncludePermissions
	}
	return false
}

func (x *ValidateTokenRequest) GetIncludeOrganization() bool {
	if x != nil {
		return x.IncludeOrganization
	}
	return false
}

func (x *ValidateTokenRequest) GetRequiredPermissions() []string {
	if x != nil {
		return x.RequiredPermissions
	}
	return nil
}

func (x *ValidateTokenRequest) GetResourceContext() string {
	if x != nil {
		return x.ResourceContext
	}
	return ""
}

func (x *ValidateTokenRequest) GetStrictValidation() bool {
	if x != nil {
		return x.StrictValidation
	}
	return false
}

// JWT Token Validation Response
type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Valid         bool                   `protobuf:"varint,3,opt,name=valid,proto3" json:"valid,omitempty"`
	Claims        *TokenClaims           `protobuf:"bytes,4,opt,name=claims,proto3" json:"claims,omitempty"`
	UserContext   *UserContext           `protobuf:"bytes,5,opt,name=user_context,json=userContext,proto3" json:"user_context,omitempty"`
	Permissions   []string               `protobuf:"bytes,6,rep,name=permissions,proto3" json:"permissions,omitempty"`
	Organization  *Organization          `protobuf:"bytes,7,opt,name=organization,proto3" json:"organization,omitempty"`
	ValidationId  string                 `protobuf:"bytes,8,opt,name=validation_id,json=validationId,proto3" json:"validation_id,omitempty"`
	ValidatedAt   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=validated_at,json=validatedAt,proto3" json:"validated_at,omitempty"`
	Warnings      []string               `protobuf:"bytes,10,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_token_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_token_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_token_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateTokenResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ValidateTokenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidateTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateTokenResponse) GetClaims() *TokenClaims {
	if x != nil {
		return x.Claims
	}
	return nil
}

func (x *ValidateTokenResponse) GetUserContext() *UserContext {
	if x != nil {
		return x.UserContext
	}
	return nil
}

func (x *ValidateTokenResponse) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *ValidateTokenResponse) GetOrganization() *Organization {
	if x != nil {
		return x.Organization
	}
	return nil
}

func (x *ValidateTokenResponse) GetValidationId() string {
	if x != nil {
		return x.ValidationId
	}
	return ""
}

func (x *ValidateTokenResponse) GetValidatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidatedAt
	}
	return nil
}

func (x *ValidateTokenResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

// Token Claims
type TokenClaims struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username         string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email            string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	OrganizationId   string                 `protobuf:"bytes,4,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	OrganizationName string                 `protobuf:"bytes,5,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	Roles            []string               `protobuf:"bytes,6,rep,name=roles,proto3" json:"roles,omitempty"`
	Permissions      []string               `protobuf:"bytes,7,rep,name=permissions,proto3" json:"permissions,omitempty"`
	SessionId        string                 `protobuf:"bytes,8,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	DeviceId         string                 `protobuf:"bytes,9,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	IssuedAt         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt        *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	NotBefore        *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	Issuer           string                 `protobuf:"bytes,13,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Audience         []string               `protobuf:"bytes,14,rep,name=audience,proto3" json:"audience,omitempty"`
	Subject          string                 `protobuf:"bytes,15,opt,name=subject,proto3" json:"subject,omitempty"`
	Jti              string                 `protobuf:"bytes,16,opt,name=jti,proto3" json:"jti,omitempty"`
	CustomClaims     *structpb.Struct       `protobuf:"bytes,17,opt,name=custom_claims,json=customClaims,proto3" json:"custom_claims,omitempty"`
	TokenType        string                 `protobuf:"bytes,18,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	Scopes           []string               `protobuf:"bytes,19,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TokenClaims) Reset() {
	*x = TokenClaims{}
	mi := &file_token_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenClaims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenClaims) ProtoMessage() {}

func (x *TokenClaims) ProtoReflect() protoreflect.Message {
	mi := &file_token_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenClaims.ProtoReflect.Descriptor instead.
func (*TokenClaims) Descriptor() ([]byte, []int) {
	return file_token_proto_rawDescGZIP(), []int{2}
}

func (x *TokenClaims) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TokenClaims) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TokenClaims) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *TokenClaims) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *TokenClaims) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

func (x *TokenClaims) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *TokenClaims) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *TokenClaims) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TokenClaims) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *TokenClaims) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *TokenClaims) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *TokenClaims) GetNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *TokenClaims) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *TokenClaims) GetAudience() []string {
	if x != nil {
		return x.Audience
	}
	return nil
}

func (x *TokenClaims) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *TokenClaims) GetJti() string {
	if x != nil {
		return x.Jti
	}
	return ""
}

func (x *TokenClaims) GetCustomClaims() *structpb.Struct {
	if x != nil {
		return x.CustomClaims
	}
	return nil
}

func (x *TokenClaims) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *TokenClaims) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

// User Context for token validation
type UserContext struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username          string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email             string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	FullName          string                 `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Status            string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	IsValidated       bool                   `protobuf:"varint,6,opt,name=is_validated,json=isValidated,proto3" json:"is_validated,omitempty"`
	OrganizationId    string                 `protobuf:"bytes,7,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	OrganizationName  string                 `protobuf:"bytes,8,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	Roles             []string               `protobuf:"bytes,9,rep,name=roles,proto3" json:"roles,omitempty"`
	Permissions       []string               `protobuf:"bytes,10,rep,name=permissions,proto3" json:"permissions,omitempty"`
	Groups            []string               `protobuf:"bytes,11,rep,name=groups,proto3" json:"groups,omitempty"`
	Metadata          *structpb.Struct       `protobuf:"bytes,12,opt,name=metadata,proto3" json:"metadata,omitempty"`
	PreferredLanguage string                 `protobuf:"bytes,13,opt,name=preferred_language,json=preferredLanguage,proto3" json:"preferred_language,omitempty"`
	Timezone          string                 `protobuf:"bytes,14,opt,name=timezone,proto3" json:"timezone,omitempty"`
	LastLoginAt       *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=last_login_at,json=lastLoginAt,proto3" json:"last_login_at,omitempty"`
	MfaEnabled        bool                   `protobuf:"varint,16,opt,name=mfa_enabled,json=mfaEnabled,proto3" json:"mfa_enabled,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserContext) Reset() {
	*x = UserContext{}
	mi := &file_token_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserContext) ProtoMessage() {}

func (x *UserContext) ProtoReflect() protoreflect.Message {
	mi := &file_token_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserContext.ProtoReflect.Descriptor instead.
func (*UserContext) Descriptor() ([]byte, []int) {
	return file_token_proto_rawDescGZIP(), []int{3}
}

func (x *UserContext) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserContext) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserContext) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserContext) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UserContext) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UserContext) GetIsValidated() bool {
	if x != nil {
		return x.IsValidated
	}
	return false
}

func (x *UserContext) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *UserContext) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

func (x *UserContext) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *UserContext) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *UserContext) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *UserContext) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UserContext) GetPreferredLanguage() string {
	if x != nil {
		return x.PreferredLanguage
	}
	return ""
}

func (x *UserContext) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *UserContext) GetLastLoginAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLoginAt
	}
	return nil
}

func (x *UserContext) GetMfaEnabled() bool {
	if x != nil {
		return x.MfaEnabled
	}
	return false
}

// Token Refresh Request
type RefreshAccessTokenRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken    string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	DeviceId        string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	RequestedScopes []string               `protobuf:"bytes,3,rep,name=requested_scopes,json=requestedScopes,proto3" json:"requested_scopes,omitempty"`
	OrganizationId  string                 `protobuf:"bytes,4,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ExtendSession   bool                   `protobuf:"varint,5,opt,name=extend_session,json=extendSession,proto3" json:"extend_session,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RefreshAccessTokenRequest) Reset() {
	*x = RefreshAccessTokenRequest{}
	mi := &file_token_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshAccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAccessTokenRequest) ProtoMessage() {}

func (x *RefreshAccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_token_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAccessTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshAccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_token_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshAccessTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshAccessTokenRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RefreshAccessTokenRequest) GetRequestedScopes() []string {
	if x != nil {
		return x.RequestedScopes
	}
	return nil
}

func (x *RefreshAccessTokenRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *RefreshAccessTokenRequest) GetExtendSession() bool {
	if x != nil {
		return x.ExtendSession
	}
	return false
}

// Token Refresh Response
type RefreshAccessTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AccessToken   string                 `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	TokenType     string                 `protobuf:"bytes,5,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	ExpiresIn     int32                  `protobuf:"varint,6,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	GrantedScopes []string               `protobuf:"bytes,7,rep,name=granted_scopes,json=grantedScopes,proto3" json:"granted_scopes,omitempty"`
	Claims        *TokenClaims           `protobuf:"bytes,8,opt,name=claims,proto3" json:"claims,omitempty"`
	UserContext   *UserContext           `protobuf:"bytes,9,opt,name=user_context,json=userContext,proto3" json:"user_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshAccessTokenResponse) Reset() {
	*x = RefreshAccessTokenResponse{}
	mi := &file_token_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshAccessTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAccessTokenResponse) ProtoMessage() {}

func (x *RefreshAccessTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_token_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAccessTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshAccessTokenResponse) Descriptor() ([]byte, []int) {
	return file_token_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshAccessTokenResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *RefreshAccessTokenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RefreshAccessTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshAccessTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshAccessTokenResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *RefreshAccessTokenResponse) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *RefreshAccessTokenResponse) GetGrantedScopes() []string {
	if x != nil {
		return x.GrantedScopes
	}
	return nil
}

func (x *RefreshAccessTokenResponse) GetClaims() *TokenClaims {
	if x != nil {
		return x.Claims
	}
	return nil
}

func (x *RefreshAccessTokenResponse) GetUserContext() *UserContext {
	if x != nil {
		return x.UserContext
	}
	return nil
}

// Token Revocation Request
type RevokeTokenRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Token               string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	TokenTypeHint       string                 `protobuf:"bytes,2,opt,name=token_type_hint,json=tokenTypeHint,proto3" json:"token_type_hint,omitempty"` // "access_token" or "refresh_token"
	DeviceId            string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	RevokeAllUserTokens bool                   `protobuf:"varint,4,opt,name=revoke_all_user_tokens,json=revokeAllUserTokens,proto3" json:"revoke_all_user_tokens,omitempty"`
	Reason              string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RevokeTokenRequest) Reset() {
	*x = RevokeTokenRequest{}
	mi := &file_token_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenRequest) ProtoMessage() {}

func (x *RevokeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_token_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeTokenRequest) Descriptor() ([]byte, []int) {
	return file_token_proto_rawDescGZIP(), []int{6}
}

func (x *RevokeTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RevokeTokenRequest) GetTokenTypeHint() string {
	if x != nil {
		return x.TokenTypeHint
	}
	return ""
}

func (x *RevokeTokenRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RevokeTokenRequest) GetRevokeAllUserTokens() bool {
	if x != nil {
		return x.RevokeAllUserTokens
	}
	return false
}

func (x *RevokeTokenRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Token Revocation Response
type RevokeTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	TokensRevoked int32                  `protobuf:"varint,4,opt,name=tokens_revoked,json=tokensRevoked,proto3" json:"tokens_revoked,omitempty"`
	RevocationId  string                 `protobuf:"bytes,5,opt,name=revocation_id,json=revocationId,proto3" json:"revocation_id,omitempty"`
	RevokedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenResponse) Reset() {
	*x = RevokeTokenResponse{}
	mi := &file_token_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenResponse) ProtoMessage() {}

func (x *RevokeTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_token_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenResponse.ProtoReflect.Descriptor instead.
func (*RevokeTokenResponse) Descriptor() ([]byte, []int) {
	return file_token_proto_rawDescGZIP(), []int{7}
}

func (x *RevokeTokenResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *RevokeTokenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RevokeTokenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RevokeTokenResponse) GetTokensRevoked() int32 {
	if x != nil {
		return x.TokensRevoked
	}
	return 0
}

func (x *RevokeTokenResponse) GetRevocationId() string {
	if x != nil {
		return x.RevocationId
	}
	return ""
}

func (x *RevokeTokenResponse) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

// Token Introspection Request (OAuth 2.0 style)
type IntrospectTokenRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Token          string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	TokenTypeHint  string                 `protobuf:"bytes,2,opt,name=token_type_hint,json=tokenTypeHint,proto3" json:"token_type_hint,omitempty"`
	ResourceServer string                 `protobuf:"bytes,3,opt,name=resource_server,json=resourceServer,proto3" json:"resource_server,omitempty"`
	RequiredScopes []string               `protobuf:"bytes,4,rep,name=required_scopes,json=requiredScopes,proto3" json:"required_scopes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IntrospectTokenRequest) Reset() {
	*x = IntrospectTokenRequest{}
	mi := &file_token_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntrospectTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntrospectTokenRequest) ProtoMessage() {}

func (x *IntrospectTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_token_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntrospectTokenRequest.ProtoReflect.Descriptor instead.
func (*IntrospectTokenRequest) Descriptor() ([]byte, []int) {
	return file_token_proto_rawDescGZIP(), []int{8}
}

func (x *IntrospectTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *IntrospectTokenRequest) GetTokenTypeHint() string {
	if x != nil {
		return x.TokenTypeHint
	}
	return ""
}

func (x *IntrospectTokenRequest) GetResourceServer() string {
	if x != nil {
		return x.ResourceServer
	}
	return ""
}

func (x *IntrospectTokenRequest) GetRequiredScopes() []string {
	if x != nil {
		return x.RequiredScopes
	}
	return nil
}

// Token Introspection Response
type IntrospectTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Scope         string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	Exp           int64                  `protobuf:"varint,5,opt,name=exp,proto3" json:"exp,omitempty"`
	Iat           int64                  `protobuf:"varint,6,opt,name=iat,proto3" json:"iat,omitempty"`
	Nbf           int64                  `protobuf:"varint,7,opt,name=nbf,proto3" json:"nbf,omitempty"`
	Sub           string                 `protobuf:"bytes,8,opt,name=sub,proto3" json:"sub,omitempty"`
	Aud           []string               `protobuf:"bytes,9,rep,name=aud,proto3" json:"aud,omitempty"`
	Iss           string                 `protobuf:"bytes,10,opt,name=iss,proto3" json:"iss,omitempty"`
	Jti           string                 `protobuf:"bytes,11,opt,name=jti,proto3" json:"jti,omitempty"`
	TokenType     string                 `protobuf:"bytes,12,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	Extensions    *structpb.Struct       `protobuf:"bytes,13,opt,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntrospectTokenResponse) Reset() {
	*x = IntrospectTokenResponse{}
	mi := &file_token_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntrospectTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntrospectTokenResponse) ProtoMessage() {}

func (x *IntrospectTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_token_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntrospectTokenResponse.ProtoReflect.Descriptor instead.
func (*IntrospectTokenResponse) Descriptor() ([]byte, []int) {
	return file_token_proto_rawDescGZIP(), []int{9}
}

func (x *IntrospectTokenResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *IntrospectTokenResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *IntrospectTokenResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *IntrospectTokenResponse) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *IntrospectTokenResponse) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *IntrospectTokenResponse) GetIat() int64 {
	if x != nil {
		return x.Iat
	}
	return 0
}

func (x *IntrospectTokenResponse) GetNbf() int64 {
	if x != nil {
		return x.Nbf
	}
	return 0
}

func (x *IntrospectTokenResponse) GetSub() string {
	if x != nil {
		return x.Sub
	}
	return ""
}

func (x *IntrospectTokenResponse) GetAud() []string {
	if x != nil {
		return x.Aud
	}
	return nil
}

func (x *IntrospectTokenResponse) GetIss() string {
	if x != nil {
		return x.Iss
	}
	return ""
}

func (x *IntrospectTokenResponse) GetJti() string {
	if x != nil {
		return x.Jti
	}
	return ""
}

func (x *IntrospectTokenResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *IntrospectTokenResponse) GetExtensions() *structpb.Struct {
	if x != nil {
		return x.Extensions
	}
	return nil
}

// Create Token Request (for service-to-service)
type CreateTokenRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrganizationId   string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Roles            []string               `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	Permissions      []string               `protobuf:"bytes,4,rep,name=permissions,proto3" json:"permissions,omitempty"`
	Scopes           []string               `protobuf:"bytes,5,rep,name=scopes,proto3" json:"scopes,omitempty"`
	ExpiresInSeconds int32                  `protobuf:"varint,6,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"`
	DeviceId         string                 `protobuf:"bytes,7,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	SessionId        string                 `protobuf:"bytes,8,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CustomClaims     *structpb.Struct       `protobuf:"bytes,9,opt,name=custom_claims,json=customClaims,proto3" json:"custom_claims,omitempty"`
	TokenType        string                 `protobuf:"bytes,10,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	Audience         []string               `protobuf:"bytes,11,rep,name=audience,proto3" json:"audience,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateTokenRequest) Reset() {
	*x = CreateTokenRequest{}
	mi := &file_token_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenRequest) ProtoMessage() {}

func (x *CreateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_token_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateTokenRequest) Descriptor() ([]byte, []int) {
	return file_token_proto_rawDescGZIP(), []int{10}
}

func (x *CreateTokenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateTokenRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateTokenRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *CreateTokenRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *CreateTokenRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *CreateTokenRequest) GetExpiresInSeconds() int32 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

func (x *CreateTokenRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *CreateTokenRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateTokenRequest) GetCustomClaims() *structpb.Struct {
	if x != nil {
		return x.CustomClaims
	}
	return nil
}

func (x *CreateTokenRequest) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *CreateTokenRequest) GetAudience() []string {
	if x != nil {
		return x.Audience
	}
	return nil
}

// Create Token Response
type CreateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AccessToken   string                 `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	TokenType     string                 `protobuf:"bytes,5,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	ExpiresIn     int32                  `protobuf:"varint,6,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	Claims        *TokenClaims           `protobuf:"bytes,7,opt,name=claims,proto3" json:"claims,omitempty"`
	TokenId       string                 `protobuf:"bytes,8,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTokenResponse) Reset() {
	*x = CreateTokenResponse{}
	mi := &file_token_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenResponse) ProtoMessage() {}

func (x *CreateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_token_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateTokenResponse) Descriptor() ([]byte, []int) {
	return file_token_proto_rawDescGZIP(), []int{11}
}

func (x *CreateTokenResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *CreateTokenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *CreateTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *CreateTokenResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *CreateTokenResponse) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *CreateTokenResponse) GetClaims() *TokenClaims {
	if x != nil {
		return x.Claims
	}
	return nil
}

func (x *CreateTokenResponse) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

// List Active Tokens Request
type ListActiveTokensRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	DeviceId       string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	TokenType      string                 `protobuf:"bytes,4,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	Page           int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PerPage        int32                  `protobuf:"varint,6,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	IncludeExpired bool                   `protobuf:"varint,7,opt,name=include_expired,json=includeExpired,proto3" json:"include_expired,omitempty"`
	SortBy         string                 `protobuf:"bytes,8,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder      string                 `protobuf:"bytes,9,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListActiveTokensRequest) Reset() {
	*x = ListActiveTokensRequest{}
	mi := &file_token_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveTokensRequest) ProtoMessage() {}

func (x *ListActiveTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_token_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveTokensRequest.ProtoReflect.Descriptor instead.
func (*ListActiveTokensRequest) Descriptor() ([]byte, []int) {
	return file_token_proto_rawDescGZIP(), []int{12}
}

func (x *ListActiveTokensRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListActiveTokensRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListActiveTokensRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ListActiveTokensRequest) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *ListActiveTokensRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListActiveTokensRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *ListActiveTokensRequest) GetIncludeExpired() bool {
	if x != nil {
		return x.IncludeExpired
	}
	return false
}

func (x *ListActiveTokensRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListActiveTokensRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

// Active Token Info
type ActiveTokenInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	TokenType     string                 `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceName    string                 `protobuf:"bytes,4,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	UserAgent     string                 `protobuf:"bytes,5,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	IpAddress     string                 `protobuf:"bytes,6,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	Scopes        []string               `protobuf:"bytes,10,rep,name=scopes,proto3" json:"scopes,omitempty"`
	IsActive      bool                   `protobuf:"varint,11,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Status        string                 `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveTokenInfo) Reset() {
	*x = ActiveTokenInfo{}
	mi := &file_token_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveTokenInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveTokenInfo) ProtoMessage() {}

func (x *ActiveTokenInfo) ProtoReflect() protoreflect.Message {
	mi := &file_token_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveTokenInfo.ProtoReflect.Descriptor instead.
func (*ActiveTokenInfo) Descriptor() ([]byte, []int) {
	return file_token_proto_rawDescGZIP(), []int{13}
}

func (x *ActiveTokenInfo) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *ActiveTokenInfo) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *ActiveTokenInfo) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ActiveTokenInfo) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *ActiveTokenInfo) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *ActiveTokenInfo) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *ActiveTokenInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ActiveTokenInfo) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ActiveTokenInfo) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

func (x *ActiveTokenInfo) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *ActiveTokenInfo) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ActiveTokenInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// List Active Tokens Response
type ListActiveTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Tokens        []*ActiveTokenInfo     `protobuf:"bytes,3,rep,name=tokens,proto3" json:"tokens,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,6,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	TotalPages    int32                  `protobuf:"varint,7,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	HasNextPage   bool                   `protobuf:"varint,8,opt,name=has_next_page,json=hasNextPage,proto3" json:"has_next_page,omitempty"`
	HasPrevPage   bool                   `protobuf:"varint,9,opt,name=has_prev_page,json=hasPrevPage,proto3" json:"has_prev_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveTokensResponse) Reset() {
	*x = ListActiveTokensResponse{}
	mi := &file_token_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveTokensResponse) ProtoMessage() {}

func (x *ListActiveTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_token_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveTokensResponse.ProtoReflect.Descriptor instead.
func (*ListActiveTokensResponse) Descriptor() ([]byte, []int) {
	return file_token_proto_rawDescGZIP(), []int{14}
}

func (x *ListActiveTokensResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ListActiveTokensResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListActiveTokensResponse) GetTokens() []*ActiveTokenInfo {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *ListActiveTokensResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListActiveTokensResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListActiveTokensResponse) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *ListActiveTokensResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *ListActiveTokensResponse) GetHasNextPage() bool {
	if x != nil {
		return x.HasNextPage
	}
	return false
}

func (x *ListActiveTokensResponse) GetHasPrevPage() bool {
	if x != nil {
		return x.HasPrevPage
	}
	return false
}

// Token Blacklist Request
type BlacklistTokenRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TokenId        string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Reason         string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	BlacklistUntil *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=blacklist_until,json=blacklistUntil,proto3" json:"blacklist_until,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BlacklistTokenRequest) Reset() {
	*x = BlacklistTokenRequest{}
	mi := &file_token_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlacklistTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlacklistTokenRequest) ProtoMessage() {}

func (x *BlacklistTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_token_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlacklistTokenRequest.ProtoReflect.Descriptor instead.
func (*BlacklistTokenRequest) Descriptor() ([]byte, []int) {
	return file_token_proto_rawDescGZIP(), []int{15}
}

func (x *BlacklistTokenRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *BlacklistTokenRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *BlacklistTokenRequest) GetBlacklistUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.BlacklistUntil
	}
	return nil
}

// Token Blacklist Response
type BlacklistTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	BlacklistId   string                 `protobuf:"bytes,4,opt,name=blacklist_id,json=blacklistId,proto3" json:"blacklist_id,omitempty"`
	BlacklistedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=blacklisted_at,json=blacklistedAt,proto3" json:"blacklisted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlacklistTokenResponse) Reset() {
	*x = BlacklistTokenResponse{}
	mi := &file_token_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlacklistTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlacklistTokenResponse) ProtoMessage() {}

func (x *BlacklistTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_token_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlacklistTokenResponse.ProtoReflect.Descriptor instead.
func (*BlacklistTokenResponse) Descriptor() ([]byte, []int) {
	return file_token_proto_rawDescGZIP(), []int{16}
}

func (x *BlacklistTokenResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *BlacklistTokenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BlacklistTokenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BlacklistTokenResponse) GetBlacklistId() string {
	if x != nil {
		return x.BlacklistId
	}
	return ""
}

func (x *BlacklistTokenResponse) GetBlacklistedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.BlacklistedAt
	}
	return nil
}

var File_token_proto protoreflect.FileDescriptor

const file_token_proto_rawDesc = "" +
	"\n" +
	"\vtoken.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x12organization.proto\"\xcd\x02\n" +
	"\x14ValidateTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x120\n" +
	"\x14include_user_details\x18\x02 \x01(\bR\x12includeUserDetails\x12/\n" +
	"\x13include_permissions\x18\x03 \x01(\bR\x12includePermissions\x121\n" +
	"\x14include_organization\x18\x04 \x01(\bR\x13includeOrganization\x121\n" +
	"\x14required_permissions\x18\x05 \x03(\tR\x13requiredPermissions\x12)\n" +
	"\x10resource_context\x18\x06 \x01(\tR\x0fresourceContext\x12+\n" +
	"\x11strict_validation\x18\a \x01(\bR\x10strictValidation\"\x9d\x03\n" +
	"\x15ValidateTokenResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05valid\x18\x03 \x01(\bR\x05valid\x12'\n" +
	"\x06claims\x18\x04 \x01(\v2\x0f.pb.TokenClaimsR\x06claims\x122\n" +
	"\fuser_context\x18\x05 \x01(\v2\x0f.pb.UserContextR\vuserContext\x12 \n" +
	"\vpermissions\x18\x06 \x03(\tR\vpermissions\x124\n" +
	"\forganization\x18\a \x01(\v2\x10.pb.OrganizationR\forganization\x12#\n" +
	"\rvalidation_id\x18\b \x01(\tR\fvalidationId\x12=\n" +
	"\fvalidated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vvalidatedAt\x12\x1a\n" +
	"\bwarnings\x18\n" +
	" \x03(\tR\bwarnings\"\xa6\x05\n" +
	"\vTokenClaims\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12'\n" +
	"\x0forganization_id\x18\x04 \x01(\tR\x0eorganizationId\x12+\n" +
	"\x11organization_name\x18\x05 \x01(\tR\x10organizationName\x12\x14\n" +
	"\x05roles\x18\x06 \x03(\tR\x05roles\x12 \n" +
	"\vpermissions\x18\a \x03(\tR\vpermissions\x12\x1d\n" +
	"\n" +
	"session_id\x18\b \x01(\tR\tsessionId\x12\x1b\n" +
	"\tdevice_id\x18\t \x01(\tR\bdeviceId\x127\n" +
	"\tissued_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x129\n" +
	"\n" +
	"expires_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x129\n" +
	"\n" +
	"not_before\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tnotBefore\x12\x16\n" +
	"\x06issuer\x18\r \x01(\tR\x06issuer\x12\x1a\n" +
	"\baudience\x18\x0e \x03(\tR\baudience\x12\x18\n" +
	"\asubject\x18\x0f \x01(\tR\asubject\x12\x10\n" +
	"\x03jti\x18\x10 \x01(\tR\x03jti\x12<\n" +
	"\rcustom_claims\x18\x11 \x01(\v2\x17.google.protobuf.StructR\fcustomClaims\x12\x1d\n" +
	"\n" +
	"token_type\x18\x12 \x01(\tR\ttokenType\x12\x16\n" +
	"\x06scopes\x18\x13 \x03(\tR\x06scopes\"\xae\x04\n" +
	"\vUserContext\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1b\n" +
	"\tfull_name\x18\x04 \x01(\tR\bfullName\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12!\n" +
	"\fis_validated\x18\x06 \x01(\bR\visValidated\x12'\n" +
	"\x0forganization_id\x18\a \x01(\tR\x0eorganizationId\x12+\n" +
	"\x11organization_name\x18\b \x01(\tR\x10organizationName\x12\x14\n" +
	"\x05roles\x18\t \x03(\tR\x05roles\x12 \n" +
	"\vpermissions\x18\n" +
	" \x03(\tR\vpermissions\x12\x16\n" +
	"\x06groups\x18\v \x03(\tR\x06groups\x123\n" +
	"\bmetadata\x18\f \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12-\n" +
	"\x12preferred_language\x18\r \x01(\tR\x11preferredLanguage\x12\x1a\n" +
	"\btimezone\x18\x0e \x01(\tR\btimezone\x12>\n" +
	"\rlast_login_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\vlastLoginAt\x12\x1f\n" +
	"\vmfa_enabled\x18\x10 \x01(\bR\n" +
	"mfaEnabled\"\xd8\x01\n" +
	"\x19RefreshAccessTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12)\n" +
	"\x10requested_scopes\x18\x03 \x03(\tR\x0frequestedScopes\x12'\n" +
	"\x0forganization_id\x18\x04 \x01(\tR\x0eorganizationId\x12%\n" +
	"\x0eextend_session\x18\x05 \x01(\bR\rextendSession\"\xe1\x02\n" +
	"\x1aRefreshAccessTokenResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\faccess_token\x18\x03 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x04 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x05 \x01(\tR\ttokenType\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x06 \x01(\x05R\texpiresIn\x12%\n" +
	"\x0egranted_scopes\x18\a \x03(\tR\rgrantedScopes\x12'\n" +
	"\x06claims\x18\b \x01(\v2\x0f.pb.TokenClaimsR\x06claims\x122\n" +
	"\fuser_context\x18\t \x01(\v2\x0f.pb.UserContextR\vuserContext\"\xbc\x01\n" +
	"\x12RevokeTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12&\n" +
	"\x0ftoken_type_hint\x18\x02 \x01(\tR\rtokenTypeHint\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x123\n" +
	"\x16revoke_all_user_tokens\x18\x04 \x01(\bR\x13revokeAllUserTokens\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"\xf1\x01\n" +
	"\x13RevokeTokenResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12%\n" +
	"\x0etokens_revoked\x18\x04 \x01(\x05R\rtokensRevoked\x12#\n" +
	"\rrevocation_id\x18\x05 \x01(\tR\frevocationId\x129\n" +
	"\n" +
	"revoked_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\"\xa8\x01\n" +
	"\x16IntrospectTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12&\n" +
	"\x0ftoken_type_hint\x18\x02 \x01(\tR\rtokenTypeHint\x12'\n" +
	"\x0fresource_server\x18\x03 \x01(\tR\x0eresourceServer\x12'\n" +
	"\x0frequired_scopes\x18\x04 \x03(\tR\x0erequiredScopes\"\xd6\x02\n" +
	"\x17IntrospectTokenResponse\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\x12\x10\n" +
	"\x03exp\x18\x05 \x01(\x03R\x03exp\x12\x10\n" +
	"\x03iat\x18\x06 \x01(\x03R\x03iat\x12\x10\n" +
	"\x03nbf\x18\a \x01(\x03R\x03nbf\x12\x10\n" +
	"\x03sub\x18\b \x01(\tR\x03sub\x12\x10\n" +
	"\x03aud\x18\t \x03(\tR\x03aud\x12\x10\n" +
	"\x03iss\x18\n" +
	" \x01(\tR\x03iss\x12\x10\n" +
	"\x03jti\x18\v \x01(\tR\x03jti\x12\x1d\n" +
	"\n" +
	"token_type\x18\f \x01(\tR\ttokenType\x127\n" +
	"\n" +
	"extensions\x18\r \x01(\v2\x17.google.protobuf.StructR\n" +
	"extensions\"\x89\x03\n" +
	"\x12CreateTokenRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\x12 \n" +
	"\vpermissions\x18\x04 \x03(\tR\vpermissions\x12\x16\n" +
	"\x06scopes\x18\x05 \x03(\tR\x06scopes\x12,\n" +
	"\x12expires_in_seconds\x18\x06 \x01(\x05R\x10expiresInSeconds\x12\x1b\n" +
	"\tdevice_id\x18\a \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"session_id\x18\b \x01(\tR\tsessionId\x12<\n" +
	"\rcustom_claims\x18\t \x01(\v2\x17.google.protobuf.StructR\fcustomClaims\x12\x1d\n" +
	"\n" +
	"token_type\x18\n" +
	" \x01(\tR\ttokenType\x12\x1a\n" +
	"\baudience\x18\v \x03(\tR\baudience\"\x9a\x02\n" +
	"\x13CreateTokenResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\faccess_token\x18\x03 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x04 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x05 \x01(\tR\ttokenType\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x06 \x01(\x05R\texpiresIn\x12'\n" +
	"\x06claims\x18\a \x01(\v2\x0f.pb.TokenClaimsR\x06claims\x12\x19\n" +
	"\btoken_id\x18\b \x01(\tR\atokenId\"\xa7\x02\n" +
	"\x17ListActiveTokensRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"token_type\x18\x04 \x01(\tR\ttokenType\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x06 \x01(\x05R\aperPage\x12'\n" +
	"\x0finclude_expired\x18\a \x01(\bR\x0eincludeExpired\x12\x17\n" +
	"\asort_by\x18\b \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\t \x01(\tR\tsortOrder\"\xc8\x03\n" +
	"\x0fActiveTokenInfo\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\x12\x1d\n" +
	"\n" +
	"token_type\x18\x02 \x01(\tR\ttokenType\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vdevice_name\x18\x04 \x01(\tR\n" +
	"deviceName\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x05 \x01(\tR\tuserAgent\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x06 \x01(\tR\tipAddress\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12<\n" +
	"\flast_used_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\x12\x16\n" +
	"\x06scopes\x18\n" +
	" \x03(\tR\x06scopes\x12\x1b\n" +
	"\tis_active\x18\v \x01(\bR\bisActive\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\"\xbb\x02\n" +
	"\x18ListActiveTokensResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x06tokens\x18\x03 \x03(\v2\x13.pb.ActiveTokenInfoR\x06tokens\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x06 \x01(\x05R\aperPage\x12\x1f\n" +
	"\vtotal_pages\x18\a \x01(\x05R\n" +
	"totalPages\x12\"\n" +
	"\rhas_next_page\x18\b \x01(\bR\vhasNextPage\x12\"\n" +
	"\rhas_prev_page\x18\t \x01(\bR\vhasPrevPage\"\x8f\x01\n" +
	"\x15BlacklistTokenRequest\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12C\n" +
	"\x0fblacklist_until\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0eblacklistUntil\"\xd3\x01\n" +
	"\x16BlacklistTokenResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12!\n" +
	"\fblacklist_id\x18\x04 \x01(\tR\vblacklistId\x12A\n" +
	"\x0eblacklisted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rblacklistedAt2\x8d\x04\n" +
	"\fTokenService\x12D\n" +
	"\rValidateToken\x12\x18.pb.ValidateTokenRequest\x1a\x19.pb.ValidateTokenResponse\x12S\n" +
	"\x12RefreshAccessToken\x12\x1d.pb.RefreshAccessTokenRequest\x1a\x1e.pb.RefreshAccessTokenResponse\x12>\n" +
	"\vRevokeToken\x12\x16.pb.RevokeTokenRequest\x1a\x17.pb.RevokeTokenResponse\x12J\n" +
	"\x0fIntrospectToken\x12\x1a.pb.IntrospectTokenRequest\x1a\x1b.pb.IntrospectTokenResponse\x12>\n" +
	"\vCreateToken\x12\x16.pb.CreateTokenRequest\x1a\x17.pb.CreateTokenResponse\x12M\n" +
	"\x10ListActiveTokens\x12\x1b.pb.ListActiveTokensRequest\x1a\x1c.pb.ListActiveTokensResponse\x12G\n" +
	"\x0eBlacklistToken\x12\x19.pb.BlacklistTokenRequest\x1a\x1a.pb.BlacklistTokenResponseB/Z-github.com/Kisanlink/farmers-module/pkg/protob\x06proto3"

var (
	file_token_proto_rawDescOnce sync.Once
	file_token_proto_rawDescData []byte
)

func file_token_proto_rawDescGZIP() []byte {
	file_token_proto_rawDescOnce.Do(func() {
		file_token_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_token_proto_rawDesc), len(file_token_proto_rawDesc)))
	})
	return file_token_proto_rawDescData
}

var file_token_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_token_proto_goTypes = []any{
	(*ValidateTokenRequest)(nil),       // 0: pb.ValidateTokenRequest
	(*ValidateTokenResponse)(nil),      // 1: pb.ValidateTokenResponse
	(*TokenClaims)(nil),                // 2: pb.TokenClaims
	(*UserContext)(nil),                // 3: pb.UserContext
	(*RefreshAccessTokenRequest)(nil),  // 4: pb.RefreshAccessTokenRequest
	(*RefreshAccessTokenResponse)(nil), // 5: pb.RefreshAccessTokenResponse
	(*RevokeTokenRequest)(nil),         // 6: pb.RevokeTokenRequest
	(*RevokeTokenResponse)(nil),        // 7: pb.RevokeTokenResponse
	(*IntrospectTokenRequest)(nil),     // 8: pb.IntrospectTokenRequest
	(*IntrospectTokenResponse)(nil),    // 9: pb.IntrospectTokenResponse
	(*CreateTokenRequest)(nil),         // 10: pb.CreateTokenRequest
	(*CreateTokenResponse)(nil),        // 11: pb.CreateTokenResponse
	(*ListActiveTokensRequest)(nil),    // 12: pb.ListActiveTokensRequest
	(*ActiveTokenInfo)(nil),            // 13: pb.ActiveTokenInfo
	(*ListActiveTokensResponse)(nil),   // 14: pb.ListActiveTokensResponse
	(*BlacklistTokenRequest)(nil),      // 15: pb.BlacklistTokenRequest
	(*BlacklistTokenResponse)(nil),     // 16: pb.BlacklistTokenResponse
	(*Organization)(nil),               // 17: pb.Organization
	(*timestamppb.Timestamp)(nil),      // 18: google.protobuf.Timestamp
	(*structpb.Struct)(nil),            // 19: google.protobuf.Struct
}
var file_token_proto_depIdxs = []int32{
	2,  // 0: pb.ValidateTokenResponse.claims:type_name -> pb.TokenClaims
	3,  // 1: pb.ValidateTokenResponse.user_context:type_name -> pb.UserContext
	17, // 2: pb.ValidateTokenResponse.organization:type_name -> pb.Organization
	18, // 3: pb.ValidateTokenResponse.validated_at:type_name -> google.protobuf.Timestamp
	18, // 4: pb.TokenClaims.issued_at:type_name -> google.protobuf.Timestamp
	18, // 5: pb.TokenClaims.expires_at:type_name -> google.protobuf.Timestamp
	18, // 6: pb.TokenClaims.not_before:type_name -> google.protobuf.Timestamp
	19, // 7: pb.TokenClaims.custom_claims:type_name -> google.protobuf.Struct
	19, // 8: pb.UserContext.metadata:type_name -> google.protobuf.Struct
	18, // 9: pb.UserContext.last_login_at:type_name -> google.protobuf.Timestamp
	2,  // 10: pb.RefreshAccessTokenResponse.claims:type_name -> pb.TokenClaims
	3,  // 11: pb.RefreshAccessTokenResponse.user_context:type_name -> pb.UserContext
	18, // 12: pb.RevokeTokenResponse.revoked_at:type_name -> google.protobuf.Timestamp
	19, // 13: pb.IntrospectTokenResponse.extensions:type_name -> google.protobuf.Struct
	19, // 14: pb.CreateTokenRequest.custom_claims:type_name -> google.protobuf.Struct
	2,  // 15: pb.CreateTokenResponse.claims:type_name -> pb.TokenClaims
	18, // 16: pb.ActiveTokenInfo.created_at:type_name -> google.protobuf.Timestamp
	18, // 17: pb.ActiveTokenInfo.expires_at:type_name -> google.protobuf.Timestamp
	18, // 18: pb.ActiveTokenInfo.last_used_at:type_name -> google.protobuf.Timestamp
	13, // 19: pb.ListActiveTokensResponse.tokens:type_name -> pb.ActiveTokenInfo
	18, // 20: pb.BlacklistTokenRequest.blacklist_until:type_name -> google.protobuf.Timestamp
	18, // 21: pb.BlacklistTokenResponse.blacklisted_at:type_name -> google.protobuf.Timestamp
	0,  // 22: pb.TokenService.ValidateToken:input_type -> pb.ValidateTokenRequest
	4,  // 23: pb.TokenService.RefreshAccessToken:input_type -> pb.RefreshAccessTokenRequest
	6,  // 24: pb.TokenService.RevokeToken:input_type -> pb.RevokeTokenRequest
	8,  // 25: pb.TokenService.IntrospectToken:input_type -> pb.IntrospectTokenRequest
	10, // 26: pb.TokenService.CreateToken:input_type -> pb.CreateTokenRequest
	12, // 27: pb.TokenService.ListActiveTokens:input_type -> pb.ListActiveTokensRequest
	15, // 28: pb.TokenService.BlacklistToken:input_type -> pb.BlacklistTokenRequest
	1,  // 29: pb.TokenService.ValidateToken:output_type -> pb.ValidateTokenResponse
	5,  // 30: pb.TokenService.RefreshAccessToken:output_type -> pb.RefreshAccessTokenResponse
	7,  // 31: pb.TokenService.RevokeToken:output_type -> pb.RevokeTokenResponse
	9,  // 32: pb.TokenService.IntrospectToken:output_type -> pb.IntrospectTokenResponse
	11, // 33: pb.TokenService.CreateToken:output_type -> pb.CreateTokenResponse
	14, // 34: pb.TokenService.ListActiveTokens:output_type -> pb.ListActiveTokensResponse
	16, // 35: pb.TokenService.BlacklistToken:output_type -> pb.BlacklistTokenResponse
	29, // [29:36] is the sub-list for method output_type
	22, // [22:29] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_token_proto_init() }
func file_token_proto_init() {
	if File_token_proto != nil {
		return
	}
	file_organization_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_token_proto_rawDesc), len(file_token_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_token_proto_goTypes,
		DependencyIndexes: file_token_proto_depIdxs,
		MessageInfos:      file_token_proto_msgTypes,
	}.Build()
	File_token_proto = out.File
	file_token_proto_goTypes = nil
	file_token_proto_depIdxs = nil
}
